package com.sinosoft.platform.core.domain.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DefPrivilegeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public DefPrivilegeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeIsNull() {
            addCriterion("PRIVILEGECODE is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeIsNotNull() {
            addCriterion("PRIVILEGECODE is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeEqualTo(String value) {
            addCriterion("PRIVILEGECODE =", value, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeNotEqualTo(String value) {
            addCriterion("PRIVILEGECODE <>", value, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeGreaterThan(String value) {
            addCriterion("PRIVILEGECODE >", value, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeGreaterThanOrEqualTo(String value) {
            addCriterion("PRIVILEGECODE >=", value, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeLessThan(String value) {
            addCriterion("PRIVILEGECODE <", value, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeLessThanOrEqualTo(String value) {
            addCriterion("PRIVILEGECODE <=", value, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeLike(String value) {
            addCriterion("PRIVILEGECODE like", value, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeNotLike(String value) {
            addCriterion("PRIVILEGECODE not like", value, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeIn(List<String> values) {
            addCriterion("PRIVILEGECODE in", values, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeNotIn(List<String> values) {
            addCriterion("PRIVILEGECODE not in", values, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeBetween(String value1, String value2) {
            addCriterion("PRIVILEGECODE between", value1, value2, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegecodeNotBetween(String value1, String value2) {
            addCriterion("PRIVILEGECODE not between", value1, value2, "privilegecode");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameIsNull() {
            addCriterion("PRIVILEGENAME is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameIsNotNull() {
            addCriterion("PRIVILEGENAME is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameEqualTo(String value) {
            addCriterion("PRIVILEGENAME =", value, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameNotEqualTo(String value) {
            addCriterion("PRIVILEGENAME <>", value, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameGreaterThan(String value) {
            addCriterion("PRIVILEGENAME >", value, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameGreaterThanOrEqualTo(String value) {
            addCriterion("PRIVILEGENAME >=", value, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameLessThan(String value) {
            addCriterion("PRIVILEGENAME <", value, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameLessThanOrEqualTo(String value) {
            addCriterion("PRIVILEGENAME <=", value, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameLike(String value) {
            addCriterion("PRIVILEGENAME like", value, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameNotLike(String value) {
            addCriterion("PRIVILEGENAME not like", value, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameIn(List<String> values) {
            addCriterion("PRIVILEGENAME in", values, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameNotIn(List<String> values) {
            addCriterion("PRIVILEGENAME not in", values, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameBetween(String value1, String value2) {
            addCriterion("PRIVILEGENAME between", value1, value2, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegenameNotBetween(String value1, String value2) {
            addCriterion("PRIVILEGENAME not between", value1, value2, "privilegename");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeIsNull() {
            addCriterion("PRIVILEGETYPE is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeIsNotNull() {
            addCriterion("PRIVILEGETYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeEqualTo(String value) {
            addCriterion("PRIVILEGETYPE =", value, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeNotEqualTo(String value) {
            addCriterion("PRIVILEGETYPE <>", value, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeGreaterThan(String value) {
            addCriterion("PRIVILEGETYPE >", value, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeGreaterThanOrEqualTo(String value) {
            addCriterion("PRIVILEGETYPE >=", value, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeLessThan(String value) {
            addCriterion("PRIVILEGETYPE <", value, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeLessThanOrEqualTo(String value) {
            addCriterion("PRIVILEGETYPE <=", value, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeLike(String value) {
            addCriterion("PRIVILEGETYPE like", value, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeNotLike(String value) {
            addCriterion("PRIVILEGETYPE not like", value, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeIn(List<String> values) {
            addCriterion("PRIVILEGETYPE in", values, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeNotIn(List<String> values) {
            addCriterion("PRIVILEGETYPE not in", values, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeBetween(String value1, String value2) {
            addCriterion("PRIVILEGETYPE between", value1, value2, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andPrivilegetypeNotBetween(String value1, String value2) {
            addCriterion("PRIVILEGETYPE not between", value1, value2, "privilegetype");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("URL in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("URL not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("PID is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("PID is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("PID =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("PID <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("PID >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("PID >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("PID <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("PID <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("PID like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("PID not like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("PID in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("PID not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("PID between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("PID not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andMethodIsNull() {
            addCriterion("METHOD is null");
            return (Criteria) this;
        }

        public Criteria andMethodIsNotNull() {
            addCriterion("METHOD is not null");
            return (Criteria) this;
        }

        public Criteria andMethodEqualTo(String value) {
            addCriterion("METHOD =", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotEqualTo(String value) {
            addCriterion("METHOD <>", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThan(String value) {
            addCriterion("METHOD >", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThanOrEqualTo(String value) {
            addCriterion("METHOD >=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThan(String value) {
            addCriterion("METHOD <", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThanOrEqualTo(String value) {
            addCriterion("METHOD <=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLike(String value) {
            addCriterion("METHOD like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotLike(String value) {
            addCriterion("METHOD not like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodIn(List<String> values) {
            addCriterion("METHOD in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotIn(List<String> values) {
            addCriterion("METHOD not in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodBetween(String value1, String value2) {
            addCriterion("METHOD between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotBetween(String value1, String value2) {
            addCriterion("METHOD not between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andPreIsNull() {
            addCriterion("PRE is null");
            return (Criteria) this;
        }

        public Criteria andPreIsNotNull() {
            addCriterion("PRE is not null");
            return (Criteria) this;
        }

        public Criteria andPreEqualTo(String value) {
            addCriterion("PRE =", value, "pre");
            return (Criteria) this;
        }

        public Criteria andPreNotEqualTo(String value) {
            addCriterion("PRE <>", value, "pre");
            return (Criteria) this;
        }

        public Criteria andPreGreaterThan(String value) {
            addCriterion("PRE >", value, "pre");
            return (Criteria) this;
        }

        public Criteria andPreGreaterThanOrEqualTo(String value) {
            addCriterion("PRE >=", value, "pre");
            return (Criteria) this;
        }

        public Criteria andPreLessThan(String value) {
            addCriterion("PRE <", value, "pre");
            return (Criteria) this;
        }

        public Criteria andPreLessThanOrEqualTo(String value) {
            addCriterion("PRE <=", value, "pre");
            return (Criteria) this;
        }

        public Criteria andPreLike(String value) {
            addCriterion("PRE like", value, "pre");
            return (Criteria) this;
        }

        public Criteria andPreNotLike(String value) {
            addCriterion("PRE not like", value, "pre");
            return (Criteria) this;
        }

        public Criteria andPreIn(List<String> values) {
            addCriterion("PRE in", values, "pre");
            return (Criteria) this;
        }

        public Criteria andPreNotIn(List<String> values) {
            addCriterion("PRE not in", values, "pre");
            return (Criteria) this;
        }

        public Criteria andPreBetween(String value1, String value2) {
            addCriterion("PRE between", value1, value2, "pre");
            return (Criteria) this;
        }

        public Criteria andPreNotBetween(String value1, String value2) {
            addCriterion("PRE not between", value1, value2, "pre");
            return (Criteria) this;
        }

        public Criteria andNextIsNull() {
            addCriterion("NEXT is null");
            return (Criteria) this;
        }

        public Criteria andNextIsNotNull() {
            addCriterion("NEXT is not null");
            return (Criteria) this;
        }

        public Criteria andNextEqualTo(String value) {
            addCriterion("NEXT =", value, "next");
            return (Criteria) this;
        }

        public Criteria andNextNotEqualTo(String value) {
            addCriterion("NEXT <>", value, "next");
            return (Criteria) this;
        }

        public Criteria andNextGreaterThan(String value) {
            addCriterion("NEXT >", value, "next");
            return (Criteria) this;
        }

        public Criteria andNextGreaterThanOrEqualTo(String value) {
            addCriterion("NEXT >=", value, "next");
            return (Criteria) this;
        }

        public Criteria andNextLessThan(String value) {
            addCriterion("NEXT <", value, "next");
            return (Criteria) this;
        }

        public Criteria andNextLessThanOrEqualTo(String value) {
            addCriterion("NEXT <=", value, "next");
            return (Criteria) this;
        }

        public Criteria andNextLike(String value) {
            addCriterion("NEXT like", value, "next");
            return (Criteria) this;
        }

        public Criteria andNextNotLike(String value) {
            addCriterion("NEXT not like", value, "next");
            return (Criteria) this;
        }

        public Criteria andNextIn(List<String> values) {
            addCriterion("NEXT in", values, "next");
            return (Criteria) this;
        }

        public Criteria andNextNotIn(List<String> values) {
            addCriterion("NEXT not in", values, "next");
            return (Criteria) this;
        }

        public Criteria andNextBetween(String value1, String value2) {
            addCriterion("NEXT between", value1, value2, "next");
            return (Criteria) this;
        }

        public Criteria andNextNotBetween(String value1, String value2) {
            addCriterion("NEXT not between", value1, value2, "next");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("NUM is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("NUM is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Long value) {
            addCriterion("NUM =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Long value) {
            addCriterion("NUM <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Long value) {
            addCriterion("NUM >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Long value) {
            addCriterion("NUM >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Long value) {
            addCriterion("NUM <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Long value) {
            addCriterion("NUM <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Long> values) {
            addCriterion("NUM in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Long> values) {
            addCriterion("NUM not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Long value1, Long value2) {
            addCriterion("NUM between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Long value1, Long value2) {
            addCriterion("NUM not between", value1, value2, "num");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated do_not_delete_during_merge Thu May 12 09:48:03 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_DEF_PRIVILEGE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}