package com.sinosoft.platform.core.domain.model;

import java.math.BigDecimal;

public class TDefJdbc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.ID
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.JDBC_TYPE
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private String jdbcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.JDBC_CODE
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private String jdbcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.JDBC_NAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private String jdbcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.DRIVER_NAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private String driverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.URL
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.USERNAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.PASSWORD
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.JNDI_NAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private String jndiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.DIALECT
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private String dialect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_JDBC.DESCRIPTION
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.ID
     *
     * @return the value of T_DEF_JDBC.ID
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.ID
     *
     * @param id the value for T_DEF_JDBC.ID
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.JDBC_TYPE
     *
     * @return the value of T_DEF_JDBC.JDBC_TYPE
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public String getJdbcType() {
        return jdbcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.JDBC_TYPE
     *
     * @param jdbcType the value for T_DEF_JDBC.JDBC_TYPE
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setJdbcType(String jdbcType) {
        this.jdbcType = jdbcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.JDBC_CODE
     *
     * @return the value of T_DEF_JDBC.JDBC_CODE
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public String getJdbcCode() {
        return jdbcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.JDBC_CODE
     *
     * @param jdbcCode the value for T_DEF_JDBC.JDBC_CODE
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setJdbcCode(String jdbcCode) {
        this.jdbcCode = jdbcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.JDBC_NAME
     *
     * @return the value of T_DEF_JDBC.JDBC_NAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public String getJdbcName() {
        return jdbcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.JDBC_NAME
     *
     * @param jdbcName the value for T_DEF_JDBC.JDBC_NAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setJdbcName(String jdbcName) {
        this.jdbcName = jdbcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.DRIVER_NAME
     *
     * @return the value of T_DEF_JDBC.DRIVER_NAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.DRIVER_NAME
     *
     * @param driverName the value for T_DEF_JDBC.DRIVER_NAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.URL
     *
     * @return the value of T_DEF_JDBC.URL
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.URL
     *
     * @param url the value for T_DEF_JDBC.URL
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.USERNAME
     *
     * @return the value of T_DEF_JDBC.USERNAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.USERNAME
     *
     * @param username the value for T_DEF_JDBC.USERNAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.PASSWORD
     *
     * @return the value of T_DEF_JDBC.PASSWORD
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.PASSWORD
     *
     * @param password the value for T_DEF_JDBC.PASSWORD
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.JNDI_NAME
     *
     * @return the value of T_DEF_JDBC.JNDI_NAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public String getJndiName() {
        return jndiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.JNDI_NAME
     *
     * @param jndiName the value for T_DEF_JDBC.JNDI_NAME
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setJndiName(String jndiName) {
        this.jndiName = jndiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.DIALECT
     *
     * @return the value of T_DEF_JDBC.DIALECT
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public String getDialect() {
        return dialect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.DIALECT
     *
     * @param dialect the value for T_DEF_JDBC.DIALECT
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setDialect(String dialect) {
        this.dialect = dialect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_JDBC.DESCRIPTION
     *
     * @return the value of T_DEF_JDBC.DESCRIPTION
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_JDBC.DESCRIPTION
     *
     * @param description the value for T_DEF_JDBC.DESCRIPTION
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}