package com.sinosoft.platform.core.domain.model;

import java.math.BigDecimal;

public class TDefPlatRoleRela {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_PLAT_ROLE_RELA.ID
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_PLAT_ROLE_RELA.ROLE_ID
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    private BigDecimal roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_PLAT_ROLE_RELA.COM_ID
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    private BigDecimal comId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_PLAT_ROLE_RELA.ID
     *
     * @return the value of T_DEF_PLAT_ROLE_RELA.ID
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_PLAT_ROLE_RELA.ID
     *
     * @param id the value for T_DEF_PLAT_ROLE_RELA.ID
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_PLAT_ROLE_RELA.ROLE_ID
     *
     * @return the value of T_DEF_PLAT_ROLE_RELA.ROLE_ID
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    public BigDecimal getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_PLAT_ROLE_RELA.ROLE_ID
     *
     * @param roleId the value for T_DEF_PLAT_ROLE_RELA.ROLE_ID
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    public void setRoleId(BigDecimal roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_PLAT_ROLE_RELA.COM_ID
     *
     * @return the value of T_DEF_PLAT_ROLE_RELA.COM_ID
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    public BigDecimal getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_PLAT_ROLE_RELA.COM_ID
     *
     * @param comId the value for T_DEF_PLAT_ROLE_RELA.COM_ID
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    public void setComId(BigDecimal comId) {
        this.comId = comId;
    }
    
    //新增USER_ID 字段
    private BigDecimal userId;
    public BigDecimal getUserId(){
    	return userId;
    }
    public void setUserId(BigDecimal userId){
    	this.userId = userId;
    }
    
    //新增USER_CODE 字段
    private String userCode;
    public String getUserCode(){
    	return userCode;
    }
    public void setUserCode(String userCode){
    	this.userCode = userCode;
    }
}