package com.sinosoft.platform.core.domain.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TDefSqlExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public TDefSqlExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andSqlIdIsNull() {
			addCriterion("SQL_ID is null");
			return (Criteria) this;
		}

		public Criteria andSqlIdIsNotNull() {
			addCriterion("SQL_ID is not null");
			return (Criteria) this;
		}

		public Criteria andSqlIdEqualTo(BigDecimal value) {
			addCriterion("SQL_ID =", value, "sqlId");
			return (Criteria) this;
		}

		public Criteria andSqlIdNotEqualTo(BigDecimal value) {
			addCriterion("SQL_ID <>", value, "sqlId");
			return (Criteria) this;
		}

		public Criteria andSqlIdGreaterThan(BigDecimal value) {
			addCriterion("SQL_ID >", value, "sqlId");
			return (Criteria) this;
		}

		public Criteria andSqlIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("SQL_ID >=", value, "sqlId");
			return (Criteria) this;
		}

		public Criteria andSqlIdLessThan(BigDecimal value) {
			addCriterion("SQL_ID <", value, "sqlId");
			return (Criteria) this;
		}

		public Criteria andSqlIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("SQL_ID <=", value, "sqlId");
			return (Criteria) this;
		}

		public Criteria andSqlIdIn(List<BigDecimal> values) {
			addCriterion("SQL_ID in", values, "sqlId");
			return (Criteria) this;
		}

		public Criteria andSqlIdNotIn(List<BigDecimal> values) {
			addCriterion("SQL_ID not in", values, "sqlId");
			return (Criteria) this;
		}

		public Criteria andSqlIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("SQL_ID between", value1, value2, "sqlId");
			return (Criteria) this;
		}

		public Criteria andSqlIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("SQL_ID not between", value1, value2, "sqlId");
			return (Criteria) this;
		}

		public Criteria andSqlCodeIsNull() {
			addCriterion("SQL_CODE is null");
			return (Criteria) this;
		}

		public Criteria andSqlCodeIsNotNull() {
			addCriterion("SQL_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andSqlCodeEqualTo(String value) {
			addCriterion("SQL_CODE =", value, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeNotEqualTo(String value) {
			addCriterion("SQL_CODE <>", value, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeGreaterThan(String value) {
			addCriterion("SQL_CODE >", value, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeGreaterThanOrEqualTo(String value) {
			addCriterion("SQL_CODE >=", value, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeLessThan(String value) {
			addCriterion("SQL_CODE <", value, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeLessThanOrEqualTo(String value) {
			addCriterion("SQL_CODE <=", value, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeLike(String value) {
			addCriterion("SQL_CODE like", value, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeNotLike(String value) {
			addCriterion("SQL_CODE not like", value, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeIn(List<String> values) {
			addCriterion("SQL_CODE in", values, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeNotIn(List<String> values) {
			addCriterion("SQL_CODE not in", values, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeBetween(String value1, String value2) {
			addCriterion("SQL_CODE between", value1, value2, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlCodeNotBetween(String value1, String value2) {
			addCriterion("SQL_CODE not between", value1, value2, "sqlCode");
			return (Criteria) this;
		}

		public Criteria andSqlTypeIsNull() {
			addCriterion("SQL_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andSqlTypeIsNotNull() {
			addCriterion("SQL_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andSqlTypeEqualTo(String value) {
			addCriterion("SQL_TYPE =", value, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeNotEqualTo(String value) {
			addCriterion("SQL_TYPE <>", value, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeGreaterThan(String value) {
			addCriterion("SQL_TYPE >", value, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeGreaterThanOrEqualTo(String value) {
			addCriterion("SQL_TYPE >=", value, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeLessThan(String value) {
			addCriterion("SQL_TYPE <", value, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeLessThanOrEqualTo(String value) {
			addCriterion("SQL_TYPE <=", value, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeLike(String value) {
			addCriterion("SQL_TYPE like", value, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeNotLike(String value) {
			addCriterion("SQL_TYPE not like", value, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeIn(List<String> values) {
			addCriterion("SQL_TYPE in", values, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeNotIn(List<String> values) {
			addCriterion("SQL_TYPE not in", values, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeBetween(String value1, String value2) {
			addCriterion("SQL_TYPE between", value1, value2, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlTypeNotBetween(String value1, String value2) {
			addCriterion("SQL_TYPE not between", value1, value2, "sqlType");
			return (Criteria) this;
		}

		public Criteria andSqlFromIsNull() {
			addCriterion("SQL_FROM is null");
			return (Criteria) this;
		}

		public Criteria andSqlFromIsNotNull() {
			addCriterion("SQL_FROM is not null");
			return (Criteria) this;
		}

		public Criteria andSqlFromEqualTo(String value) {
			addCriterion("SQL_FROM =", value, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromNotEqualTo(String value) {
			addCriterion("SQL_FROM <>", value, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromGreaterThan(String value) {
			addCriterion("SQL_FROM >", value, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromGreaterThanOrEqualTo(String value) {
			addCriterion("SQL_FROM >=", value, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromLessThan(String value) {
			addCriterion("SQL_FROM <", value, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromLessThanOrEqualTo(String value) {
			addCriterion("SQL_FROM <=", value, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromLike(String value) {
			addCriterion("SQL_FROM like", value, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromNotLike(String value) {
			addCriterion("SQL_FROM not like", value, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromIn(List<String> values) {
			addCriterion("SQL_FROM in", values, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromNotIn(List<String> values) {
			addCriterion("SQL_FROM not in", values, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromBetween(String value1, String value2) {
			addCriterion("SQL_FROM between", value1, value2, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromNotBetween(String value1, String value2) {
			addCriterion("SQL_FROM not between", value1, value2, "sqlFrom");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdIsNull() {
			addCriterion("SQL_FROM_JDBC_ID is null");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdIsNotNull() {
			addCriterion("SQL_FROM_JDBC_ID is not null");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdEqualTo(BigDecimal value) {
			addCriterion("SQL_FROM_JDBC_ID =", value, "sqlFromJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdNotEqualTo(BigDecimal value) {
			addCriterion("SQL_FROM_JDBC_ID <>", value, "sqlFromJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdGreaterThan(BigDecimal value) {
			addCriterion("SQL_FROM_JDBC_ID >", value, "sqlFromJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("SQL_FROM_JDBC_ID >=", value, "sqlFromJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdLessThan(BigDecimal value) {
			addCriterion("SQL_FROM_JDBC_ID <", value, "sqlFromJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("SQL_FROM_JDBC_ID <=", value, "sqlFromJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdIn(List<BigDecimal> values) {
			addCriterion("SQL_FROM_JDBC_ID in", values, "sqlFromJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdNotIn(List<BigDecimal> values) {
			addCriterion("SQL_FROM_JDBC_ID not in", values, "sqlFromJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("SQL_FROM_JDBC_ID between", value1, value2,
					"sqlFromJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlFromJdbcIdNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("SQL_FROM_JDBC_ID not between", value1, value2,
					"sqlFromJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoIsNull() {
			addCriterion("SQL_INTO is null");
			return (Criteria) this;
		}

		public Criteria andSqlIntoIsNotNull() {
			addCriterion("SQL_INTO is not null");
			return (Criteria) this;
		}

		public Criteria andSqlIntoEqualTo(String value) {
			addCriterion("SQL_INTO =", value, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoNotEqualTo(String value) {
			addCriterion("SQL_INTO <>", value, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoGreaterThan(String value) {
			addCriterion("SQL_INTO >", value, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoGreaterThanOrEqualTo(String value) {
			addCriterion("SQL_INTO >=", value, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoLessThan(String value) {
			addCriterion("SQL_INTO <", value, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoLessThanOrEqualTo(String value) {
			addCriterion("SQL_INTO <=", value, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoLike(String value) {
			addCriterion("SQL_INTO like", value, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoNotLike(String value) {
			addCriterion("SQL_INTO not like", value, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoIn(List<String> values) {
			addCriterion("SQL_INTO in", values, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoNotIn(List<String> values) {
			addCriterion("SQL_INTO not in", values, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoBetween(String value1, String value2) {
			addCriterion("SQL_INTO between", value1, value2, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoNotBetween(String value1, String value2) {
			addCriterion("SQL_INTO not between", value1, value2, "sqlInto");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdIsNull() {
			addCriterion("SQL_INTO_JDBC_ID is null");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdIsNotNull() {
			addCriterion("SQL_INTO_JDBC_ID is not null");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdEqualTo(BigDecimal value) {
			addCriterion("SQL_INTO_JDBC_ID =", value, "sqlIntoJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdNotEqualTo(BigDecimal value) {
			addCriterion("SQL_INTO_JDBC_ID <>", value, "sqlIntoJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdGreaterThan(BigDecimal value) {
			addCriterion("SQL_INTO_JDBC_ID >", value, "sqlIntoJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("SQL_INTO_JDBC_ID >=", value, "sqlIntoJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdLessThan(BigDecimal value) {
			addCriterion("SQL_INTO_JDBC_ID <", value, "sqlIntoJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("SQL_INTO_JDBC_ID <=", value, "sqlIntoJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdIn(List<BigDecimal> values) {
			addCriterion("SQL_INTO_JDBC_ID in", values, "sqlIntoJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdNotIn(List<BigDecimal> values) {
			addCriterion("SQL_INTO_JDBC_ID not in", values, "sqlIntoJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("SQL_INTO_JDBC_ID between", value1, value2,
					"sqlIntoJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoJdbcIdNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("SQL_INTO_JDBC_ID not between", value1, value2,
					"sqlIntoJdbcId");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableIsNull() {
			addCriterion("SQL_INTO_TARGET_TABLE is null");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableIsNotNull() {
			addCriterion("SQL_INTO_TARGET_TABLE is not null");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableEqualTo(String value) {
			addCriterion("SQL_INTO_TARGET_TABLE =", value, "sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableNotEqualTo(String value) {
			addCriterion("SQL_INTO_TARGET_TABLE <>", value,
					"sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableGreaterThan(String value) {
			addCriterion("SQL_INTO_TARGET_TABLE >", value, "sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableGreaterThanOrEqualTo(String value) {
			addCriterion("SQL_INTO_TARGET_TABLE >=", value,
					"sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableLessThan(String value) {
			addCriterion("SQL_INTO_TARGET_TABLE <", value, "sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableLessThanOrEqualTo(String value) {
			addCriterion("SQL_INTO_TARGET_TABLE <=", value,
					"sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableLike(String value) {
			addCriterion("SQL_INTO_TARGET_TABLE like", value,
					"sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableNotLike(String value) {
			addCriterion("SQL_INTO_TARGET_TABLE not like", value,
					"sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableIn(List<String> values) {
			addCriterion("SQL_INTO_TARGET_TABLE in", values,
					"sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableNotIn(List<String> values) {
			addCriterion("SQL_INTO_TARGET_TABLE not in", values,
					"sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableBetween(String value1,
				String value2) {
			addCriterion("SQL_INTO_TARGET_TABLE between", value1, value2,
					"sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlIntoTargetTableNotBetween(String value1,
				String value2) {
			addCriterion("SQL_INTO_TARGET_TABLE not between", value1, value2,
					"sqlIntoTargetTable");
			return (Criteria) this;
		}

		public Criteria andSqlNumIsNull() {
			addCriterion("SQL_NUM is null");
			return (Criteria) this;
		}

		public Criteria andSqlNumIsNotNull() {
			addCriterion("SQL_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andSqlNumEqualTo(Long value) {
			addCriterion("SQL_NUM =", value, "sqlNum");
			return (Criteria) this;
		}

		public Criteria andSqlNumNotEqualTo(Long value) {
			addCriterion("SQL_NUM <>", value, "sqlNum");
			return (Criteria) this;
		}

		public Criteria andSqlNumGreaterThan(Long value) {
			addCriterion("SQL_NUM >", value, "sqlNum");
			return (Criteria) this;
		}

		public Criteria andSqlNumGreaterThanOrEqualTo(Long value) {
			addCriterion("SQL_NUM >=", value, "sqlNum");
			return (Criteria) this;
		}

		public Criteria andSqlNumLessThan(Long value) {
			addCriterion("SQL_NUM <", value, "sqlNum");
			return (Criteria) this;
		}

		public Criteria andSqlNumLessThanOrEqualTo(Long value) {
			addCriterion("SQL_NUM <=", value, "sqlNum");
			return (Criteria) this;
		}

		public Criteria andSqlNumIn(List<Long> values) {
			addCriterion("SQL_NUM in", values, "sqlNum");
			return (Criteria) this;
		}

		public Criteria andSqlNumNotIn(List<Long> values) {
			addCriterion("SQL_NUM not in", values, "sqlNum");
			return (Criteria) this;
		}

		public Criteria andSqlNumBetween(Long value1, Long value2) {
			addCriterion("SQL_NUM between", value1, value2, "sqlNum");
			return (Criteria) this;
		}

		public Criteria andSqlNumNotBetween(Long value1, Long value2) {
			addCriterion("SQL_NUM not between", value1, value2, "sqlNum");
			return (Criteria) this;
		}

		public Criteria andSqlDescIsNull() {
			addCriterion("SQL_DESC is null");
			return (Criteria) this;
		}

		public Criteria andSqlDescIsNotNull() {
			addCriterion("SQL_DESC is not null");
			return (Criteria) this;
		}

		public Criteria andSqlDescEqualTo(String value) {
			addCriterion("SQL_DESC =", value, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescNotEqualTo(String value) {
			addCriterion("SQL_DESC <>", value, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescGreaterThan(String value) {
			addCriterion("SQL_DESC >", value, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescGreaterThanOrEqualTo(String value) {
			addCriterion("SQL_DESC >=", value, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescLessThan(String value) {
			addCriterion("SQL_DESC <", value, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescLessThanOrEqualTo(String value) {
			addCriterion("SQL_DESC <=", value, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescLike(String value) {
			addCriterion("SQL_DESC like", value, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescNotLike(String value) {
			addCriterion("SQL_DESC not like", value, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescIn(List<String> values) {
			addCriterion("SQL_DESC in", values, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescNotIn(List<String> values) {
			addCriterion("SQL_DESC not in", values, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescBetween(String value1, String value2) {
			addCriterion("SQL_DESC between", value1, value2, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andSqlDescNotBetween(String value1, String value2) {
			addCriterion("SQL_DESC not between", value1, value2, "sqlDesc");
			return (Criteria) this;
		}

		public Criteria andComIdIsNull() {
			addCriterion("COM_ID is null");
			return (Criteria) this;
		}

		public Criteria andComIdIsNotNull() {
			addCriterion("COM_ID is not null");
			return (Criteria) this;
		}

		public Criteria andComIdEqualTo(BigDecimal value) {
			addCriterion("COM_ID =", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotEqualTo(BigDecimal value) {
			addCriterion("COM_ID <>", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdGreaterThan(BigDecimal value) {
			addCriterion("COM_ID >", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("COM_ID >=", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdLessThan(BigDecimal value) {
			addCriterion("COM_ID <", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("COM_ID <=", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdIn(List<BigDecimal> values) {
			addCriterion("COM_ID in", values, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotIn(List<BigDecimal> values) {
			addCriterion("COM_ID not in", values, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COM_ID between", value1, value2, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COM_ID not between", value1, value2, "comId");
			return (Criteria) this;
		}

		public Criteria andPidIsNull() {
			addCriterion("PID is null");
			return (Criteria) this;
		}

		public Criteria andPidIsNotNull() {
			addCriterion("PID is not null");
			return (Criteria) this;
		}

		public Criteria andPidEqualTo(BigDecimal value) {
			addCriterion("PID =", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotEqualTo(BigDecimal value) {
			addCriterion("PID <>", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidGreaterThan(BigDecimal value) {
			addCriterion("PID >", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PID >=", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLessThan(BigDecimal value) {
			addCriterion("PID <", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PID <=", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidIn(List<BigDecimal> values) {
			addCriterion("PID in", values, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotIn(List<BigDecimal> values) {
			addCriterion("PID not in", values, "pid");
			return (Criteria) this;
		}

		public Criteria andPidBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PID between", value1, value2, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PID not between", value1, value2, "pid");
			return (Criteria) this;
		}

		public Criteria andPreIdIsNull() {
			addCriterion("PRE_ID is null");
			return (Criteria) this;
		}

		public Criteria andPreIdIsNotNull() {
			addCriterion("PRE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPreIdEqualTo(BigDecimal value) {
			addCriterion("PRE_ID =", value, "preId");
			return (Criteria) this;
		}

		public Criteria andPreIdNotEqualTo(BigDecimal value) {
			addCriterion("PRE_ID <>", value, "preId");
			return (Criteria) this;
		}

		public Criteria andPreIdGreaterThan(BigDecimal value) {
			addCriterion("PRE_ID >", value, "preId");
			return (Criteria) this;
		}

		public Criteria andPreIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PRE_ID >=", value, "preId");
			return (Criteria) this;
		}

		public Criteria andPreIdLessThan(BigDecimal value) {
			addCriterion("PRE_ID <", value, "preId");
			return (Criteria) this;
		}

		public Criteria andPreIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PRE_ID <=", value, "preId");
			return (Criteria) this;
		}

		public Criteria andPreIdIn(List<BigDecimal> values) {
			addCriterion("PRE_ID in", values, "preId");
			return (Criteria) this;
		}

		public Criteria andPreIdNotIn(List<BigDecimal> values) {
			addCriterion("PRE_ID not in", values, "preId");
			return (Criteria) this;
		}

		public Criteria andPreIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PRE_ID between", value1, value2, "preId");
			return (Criteria) this;
		}

		public Criteria andPreIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PRE_ID not between", value1, value2, "preId");
			return (Criteria) this;
		}

		public Criteria andNextIdIsNull() {
			addCriterion("NEXT_ID is null");
			return (Criteria) this;
		}

		public Criteria andNextIdIsNotNull() {
			addCriterion("NEXT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andNextIdEqualTo(BigDecimal value) {
			addCriterion("NEXT_ID =", value, "nextId");
			return (Criteria) this;
		}

		public Criteria andNextIdNotEqualTo(BigDecimal value) {
			addCriterion("NEXT_ID <>", value, "nextId");
			return (Criteria) this;
		}

		public Criteria andNextIdGreaterThan(BigDecimal value) {
			addCriterion("NEXT_ID >", value, "nextId");
			return (Criteria) this;
		}

		public Criteria andNextIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("NEXT_ID >=", value, "nextId");
			return (Criteria) this;
		}

		public Criteria andNextIdLessThan(BigDecimal value) {
			addCriterion("NEXT_ID <", value, "nextId");
			return (Criteria) this;
		}

		public Criteria andNextIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("NEXT_ID <=", value, "nextId");
			return (Criteria) this;
		}

		public Criteria andNextIdIn(List<BigDecimal> values) {
			addCriterion("NEXT_ID in", values, "nextId");
			return (Criteria) this;
		}

		public Criteria andNextIdNotIn(List<BigDecimal> values) {
			addCriterion("NEXT_ID not in", values, "nextId");
			return (Criteria) this;
		}

		public Criteria andNextIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("NEXT_ID between", value1, value2, "nextId");
			return (Criteria) this;
		}

		public Criteria andNextIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("NEXT_ID not between", value1, value2, "nextId");
			return (Criteria) this;
		}

		public Criteria andBussTypeIsNull() {
			addCriterion("BUSS_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andBussTypeIsNotNull() {
			addCriterion("BUSS_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andBussTypeEqualTo(String value) {
			addCriterion("BUSS_TYPE =", value, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeNotEqualTo(String value) {
			addCriterion("BUSS_TYPE <>", value, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeGreaterThan(String value) {
			addCriterion("BUSS_TYPE >", value, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeGreaterThanOrEqualTo(String value) {
			addCriterion("BUSS_TYPE >=", value, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeLessThan(String value) {
			addCriterion("BUSS_TYPE <", value, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeLessThanOrEqualTo(String value) {
			addCriterion("BUSS_TYPE <=", value, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeLike(String value) {
			addCriterion("BUSS_TYPE like", value, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeNotLike(String value) {
			addCriterion("BUSS_TYPE not like", value, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeIn(List<String> values) {
			addCriterion("BUSS_TYPE in", values, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeNotIn(List<String> values) {
			addCriterion("BUSS_TYPE not in", values, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeBetween(String value1, String value2) {
			addCriterion("BUSS_TYPE between", value1, value2, "bussType");
			return (Criteria) this;
		}

		public Criteria andBussTypeNotBetween(String value1, String value2) {
			addCriterion("BUSS_TYPE not between", value1, value2, "bussType");
			return (Criteria) this;
		}

		public Criteria andEsStatusIsNull() {
			addCriterion("ES_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andEsStatusIsNotNull() {
			addCriterion("ES_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andEsStatusEqualTo(Short value) {
			addCriterion("ES_STATUS =", value, "esStatus");
			return (Criteria) this;
		}

		public Criteria andEsStatusNotEqualTo(Short value) {
			addCriterion("ES_STATUS <>", value, "esStatus");
			return (Criteria) this;
		}

		public Criteria andEsStatusGreaterThan(Short value) {
			addCriterion("ES_STATUS >", value, "esStatus");
			return (Criteria) this;
		}

		public Criteria andEsStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("ES_STATUS >=", value, "esStatus");
			return (Criteria) this;
		}

		public Criteria andEsStatusLessThan(Short value) {
			addCriterion("ES_STATUS <", value, "esStatus");
			return (Criteria) this;
		}

		public Criteria andEsStatusLessThanOrEqualTo(Short value) {
			addCriterion("ES_STATUS <=", value, "esStatus");
			return (Criteria) this;
		}

		public Criteria andEsStatusIn(List<Short> values) {
			addCriterion("ES_STATUS in", values, "esStatus");
			return (Criteria) this;
		}

		public Criteria andEsStatusNotIn(List<Short> values) {
			addCriterion("ES_STATUS not in", values, "esStatus");
			return (Criteria) this;
		}

		public Criteria andEsStatusBetween(Short value1, Short value2) {
			addCriterion("ES_STATUS between", value1, value2, "esStatus");
			return (Criteria) this;
		}

		public Criteria andEsStatusNotBetween(Short value1, Short value2) {
			addCriterion("ES_STATUS not between", value1, value2, "esStatus");
			return (Criteria) this;
		}

		public Criteria andInsertTimeIsNull() {
			addCriterion("INSERT_TIME is null");
			return (Criteria) this;
		}

		public Criteria andInsertTimeIsNotNull() {
			addCriterion("INSERT_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andInsertTimeEqualTo(Date value) {
			addCriterionForJDBCDate("INSERT_TIME =", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("INSERT_TIME <>", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("INSERT_TIME >", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("INSERT_TIME >=", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeLessThan(Date value) {
			addCriterionForJDBCDate("INSERT_TIME <", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("INSERT_TIME <=", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeIn(List<Date> values) {
			addCriterionForJDBCDate("INSERT_TIME in", values, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("INSERT_TIME not in", values, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("INSERT_TIME between", value1, value2,
					"insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("INSERT_TIME not between", value1, value2,
					"insertTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeIsNull() {
			addCriterion("LAST_MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeIsNotNull() {
			addCriterion("LAST_MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME =", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME <>", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME >", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME >=", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeLessThan(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME <", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME <=", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeIn(List<Date> values) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME in", values,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME not in", values,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME between", value1, value2,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME not between", value1,
					value2, "lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andOperatorIsNull() {
			addCriterion("OPERATOR is null");
			return (Criteria) this;
		}

		public Criteria andOperatorIsNotNull() {
			addCriterion("OPERATOR is not null");
			return (Criteria) this;
		}

		public Criteria andOperatorEqualTo(String value) {
			addCriterion("OPERATOR =", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotEqualTo(String value) {
			addCriterion("OPERATOR <>", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorGreaterThan(String value) {
			addCriterion("OPERATOR >", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATOR >=", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorLessThan(String value) {
			addCriterion("OPERATOR <", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorLessThanOrEqualTo(String value) {
			addCriterion("OPERATOR <=", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorLike(String value) {
			addCriterion("OPERATOR like", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotLike(String value) {
			addCriterion("OPERATOR not like", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorIn(List<String> values) {
			addCriterion("OPERATOR in", values, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotIn(List<String> values) {
			addCriterion("OPERATOR not in", values, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorBetween(String value1, String value2) {
			addCriterion("OPERATOR between", value1, value2, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotBetween(String value1, String value2) {
			addCriterion("OPERATOR not between", value1, value2, "operator");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeIsNull() {
			addCriterion("SUB_BUSS_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeIsNotNull() {
			addCriterion("SUB_BUSS_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeEqualTo(String value) {
			addCriterion("SUB_BUSS_TYPE =", value, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeNotEqualTo(String value) {
			addCriterion("SUB_BUSS_TYPE <>", value, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeGreaterThan(String value) {
			addCriterion("SUB_BUSS_TYPE >", value, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeGreaterThanOrEqualTo(String value) {
			addCriterion("SUB_BUSS_TYPE >=", value, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeLessThan(String value) {
			addCriterion("SUB_BUSS_TYPE <", value, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeLessThanOrEqualTo(String value) {
			addCriterion("SUB_BUSS_TYPE <=", value, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeLike(String value) {
			addCriterion("SUB_BUSS_TYPE like", value, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeNotLike(String value) {
			addCriterion("SUB_BUSS_TYPE not like", value, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeIn(List<String> values) {
			addCriterion("SUB_BUSS_TYPE in", values, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeNotIn(List<String> values) {
			addCriterion("SUB_BUSS_TYPE not in", values, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeBetween(String value1, String value2) {
			addCriterion("SUB_BUSS_TYPE between", value1, value2, "subBussType");
			return (Criteria) this;
		}

		public Criteria andSubBussTypeNotBetween(String value1, String value2) {
			addCriterion("SUB_BUSS_TYPE not between", value1, value2,
					"subBussType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_DEF_SQL
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 15 16:31:06 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}