package com.sinosoft.ummp.domain.model;

import java.math.BigDecimal;

public class TDefMsgNode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_MSG_NODE.NODE_ID
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	private BigDecimal nodeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_MSG_NODE.NODE_PID
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	private BigDecimal nodePid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_MSG_NODE.NODE_CODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	private String nodeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_MSG_NODE.NODE_NAME
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	private String nodeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_MSG_NODE.NODE_TEXT
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	private String nodeText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_MSG_NODE.NODE_NUM
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	private Long nodeNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_MSG_NODE.RC_STATUS
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	private Short rcStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_MSG_NODE.SON_NODE_TYPE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	private Short sonNodeType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_MSG_NODE.NODE_ID
	 * @return  the value of T_DEF_MSG_NODE.NODE_ID
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public BigDecimal getNodeId() {
		return nodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_MSG_NODE.NODE_ID
	 * @param nodeId  the value for T_DEF_MSG_NODE.NODE_ID
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public void setNodeId(BigDecimal nodeId) {
		this.nodeId = nodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_MSG_NODE.NODE_PID
	 * @return  the value of T_DEF_MSG_NODE.NODE_PID
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public BigDecimal getNodePid() {
		return nodePid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_MSG_NODE.NODE_PID
	 * @param nodePid  the value for T_DEF_MSG_NODE.NODE_PID
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public void setNodePid(BigDecimal nodePid) {
		this.nodePid = nodePid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_MSG_NODE.NODE_CODE
	 * @return  the value of T_DEF_MSG_NODE.NODE_CODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public String getNodeCode() {
		return nodeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_MSG_NODE.NODE_CODE
	 * @param nodeCode  the value for T_DEF_MSG_NODE.NODE_CODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public void setNodeCode(String nodeCode) {
		this.nodeCode = nodeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_MSG_NODE.NODE_NAME
	 * @return  the value of T_DEF_MSG_NODE.NODE_NAME
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public String getNodeName() {
		return nodeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_MSG_NODE.NODE_NAME
	 * @param nodeName  the value for T_DEF_MSG_NODE.NODE_NAME
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_MSG_NODE.NODE_TEXT
	 * @return  the value of T_DEF_MSG_NODE.NODE_TEXT
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public String getNodeText() {
		return nodeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_MSG_NODE.NODE_TEXT
	 * @param nodeText  the value for T_DEF_MSG_NODE.NODE_TEXT
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public void setNodeText(String nodeText) {
		this.nodeText = nodeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_MSG_NODE.NODE_NUM
	 * @return  the value of T_DEF_MSG_NODE.NODE_NUM
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public Long getNodeNum() {
		return nodeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_MSG_NODE.NODE_NUM
	 * @param nodeNum  the value for T_DEF_MSG_NODE.NODE_NUM
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public void setNodeNum(Long nodeNum) {
		this.nodeNum = nodeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_MSG_NODE.RC_STATUS
	 * @return  the value of T_DEF_MSG_NODE.RC_STATUS
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public Short getRcStatus() {
		return rcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_MSG_NODE.RC_STATUS
	 * @param rcStatus  the value for T_DEF_MSG_NODE.RC_STATUS
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public void setRcStatus(Short rcStatus) {
		this.rcStatus = rcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_MSG_NODE.SON_NODE_TYPE
	 * @return  the value of T_DEF_MSG_NODE.SON_NODE_TYPE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public Short getSonNodeType() {
		return sonNodeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_MSG_NODE.SON_NODE_TYPE
	 * @param sonNodeType  the value for T_DEF_MSG_NODE.SON_NODE_TYPE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	public void setSonNodeType(Short sonNodeType) {
		this.sonNodeType = sonNodeType;
	}

	@Override
	public String toString() {
		return "TDefMsgNode [nodeId=" + nodeId + ", nodePid=" + nodePid
				+ ", nodeCode=" + nodeCode + ", nodeName=" + nodeName
				+ ", nodeText=" + nodeText + ", nodeNum=" + nodeNum
				+ ", rcStatus=" + rcStatus + ", sonNodeType=" + sonNodeType
				+ "]";
	}
	
}