package com.sinosoft.ummp.domain.model;

public class TDefSftp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.ID
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.SFTP_IP
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private String sftpIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.SFTP_PORT
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private String sftpPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.SFTP_TYPE
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private String sftpType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.SFTP_DISC
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private String sftpDisc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.SFTP_USE_TYPE
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private String sftpUseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.VISIT_USER
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private String visitUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.VISIT_PASS
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private String visitPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.VISIT_URL
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private String visitUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.IS_NEED_KEY
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private Short isNeedKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.VISIT_KEY
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private String visitKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.COM_ID
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.ROLE_ID
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.ES_STATUS
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private Short esStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SFTP.REMARK
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.ID
     *
     * @return the value of T_DEF_SFTP.ID
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.ID
     *
     * @param id the value for T_DEF_SFTP.ID
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.SFTP_IP
     *
     * @return the value of T_DEF_SFTP.SFTP_IP
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public String getSftpIp() {
        return sftpIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.SFTP_IP
     *
     * @param sftpIp the value for T_DEF_SFTP.SFTP_IP
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setSftpIp(String sftpIp) {
        this.sftpIp = sftpIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.SFTP_PORT
     *
     * @return the value of T_DEF_SFTP.SFTP_PORT
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public String getSftpPort() {
        return sftpPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.SFTP_PORT
     *
     * @param sftpPort the value for T_DEF_SFTP.SFTP_PORT
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setSftpPort(String sftpPort) {
        this.sftpPort = sftpPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.SFTP_TYPE
     *
     * @return the value of T_DEF_SFTP.SFTP_TYPE
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public String getSftpType() {
        return sftpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.SFTP_TYPE
     *
     * @param sftpType the value for T_DEF_SFTP.SFTP_TYPE
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setSftpType(String sftpType) {
        this.sftpType = sftpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.SFTP_DISC
     *
     * @return the value of T_DEF_SFTP.SFTP_DISC
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public String getSftpDisc() {
        return sftpDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.SFTP_DISC
     *
     * @param sftpDisc the value for T_DEF_SFTP.SFTP_DISC
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setSftpDisc(String sftpDisc) {
        this.sftpDisc = sftpDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.SFTP_USE_TYPE
     *
     * @return the value of T_DEF_SFTP.SFTP_USE_TYPE
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public String getSftpUseType() {
        return sftpUseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.SFTP_USE_TYPE
     *
     * @param sftpUseType the value for T_DEF_SFTP.SFTP_USE_TYPE
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setSftpUseType(String sftpUseType) {
        this.sftpUseType = sftpUseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.VISIT_USER
     *
     * @return the value of T_DEF_SFTP.VISIT_USER
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public String getVisitUser() {
        return visitUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.VISIT_USER
     *
     * @param visitUser the value for T_DEF_SFTP.VISIT_USER
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setVisitUser(String visitUser) {
        this.visitUser = visitUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.VISIT_PASS
     *
     * @return the value of T_DEF_SFTP.VISIT_PASS
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public String getVisitPass() {
        return visitPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.VISIT_PASS
     *
     * @param visitPass the value for T_DEF_SFTP.VISIT_PASS
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setVisitPass(String visitPass) {
        this.visitPass = visitPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.VISIT_URL
     *
     * @return the value of T_DEF_SFTP.VISIT_URL
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public String getVisitUrl() {
        return visitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.VISIT_URL
     *
     * @param visitUrl the value for T_DEF_SFTP.VISIT_URL
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setVisitUrl(String visitUrl) {
        this.visitUrl = visitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.IS_NEED_KEY
     *
     * @return the value of T_DEF_SFTP.IS_NEED_KEY
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public Short getIsNeedKey() {
        return isNeedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.IS_NEED_KEY
     *
     * @param isNeedKey the value for T_DEF_SFTP.IS_NEED_KEY
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setIsNeedKey(Short isNeedKey) {
        this.isNeedKey = isNeedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.VISIT_KEY
     *
     * @return the value of T_DEF_SFTP.VISIT_KEY
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public String getVisitKey() {
        return visitKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.VISIT_KEY
     *
     * @param visitKey the value for T_DEF_SFTP.VISIT_KEY
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setVisitKey(String visitKey) {
        this.visitKey = visitKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.COM_ID
     *
     * @return the value of T_DEF_SFTP.COM_ID
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.COM_ID
     *
     * @param comId the value for T_DEF_SFTP.COM_ID
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.ROLE_ID
     *
     * @return the value of T_DEF_SFTP.ROLE_ID
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.ROLE_ID
     *
     * @param roleId the value for T_DEF_SFTP.ROLE_ID
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.ES_STATUS
     *
     * @return the value of T_DEF_SFTP.ES_STATUS
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public Short getEsStatus() {
        return esStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.ES_STATUS
     *
     * @param esStatus the value for T_DEF_SFTP.ES_STATUS
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setEsStatus(Short esStatus) {
        this.esStatus = esStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SFTP.REMARK
     *
     * @return the value of T_DEF_SFTP.REMARK
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SFTP.REMARK
     *
     * @param remark the value for T_DEF_SFTP.REMARK
     *
     * @mbggenerated Thu Jun 30 18:15:20 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}