package com.sinosoft.ummp.domain.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TDefTransexcExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public TDefTransexcExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andExcIdIsNull() {
			addCriterion("EXC_ID is null");
			return (Criteria) this;
		}

		public Criteria andExcIdIsNotNull() {
			addCriterion("EXC_ID is not null");
			return (Criteria) this;
		}

		public Criteria andExcIdEqualTo(BigDecimal value) {
			addCriterion("EXC_ID =", value, "excId");
			return (Criteria) this;
		}

		public Criteria andExcIdNotEqualTo(BigDecimal value) {
			addCriterion("EXC_ID <>", value, "excId");
			return (Criteria) this;
		}

		public Criteria andExcIdGreaterThan(BigDecimal value) {
			addCriterion("EXC_ID >", value, "excId");
			return (Criteria) this;
		}

		public Criteria andExcIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("EXC_ID >=", value, "excId");
			return (Criteria) this;
		}

		public Criteria andExcIdLessThan(BigDecimal value) {
			addCriterion("EXC_ID <", value, "excId");
			return (Criteria) this;
		}

		public Criteria andExcIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("EXC_ID <=", value, "excId");
			return (Criteria) this;
		}

		public Criteria andExcIdIn(List<BigDecimal> values) {
			addCriterion("EXC_ID in", values, "excId");
			return (Criteria) this;
		}

		public Criteria andExcIdNotIn(List<BigDecimal> values) {
			addCriterion("EXC_ID not in", values, "excId");
			return (Criteria) this;
		}

		public Criteria andExcIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("EXC_ID between", value1, value2, "excId");
			return (Criteria) this;
		}

		public Criteria andExcIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("EXC_ID not between", value1, value2, "excId");
			return (Criteria) this;
		}

		public Criteria andImplIdIsNull() {
			addCriterion("IMPL_ID is null");
			return (Criteria) this;
		}

		public Criteria andImplIdIsNotNull() {
			addCriterion("IMPL_ID is not null");
			return (Criteria) this;
		}

		public Criteria andImplIdEqualTo(BigDecimal value) {
			addCriterion("IMPL_ID =", value, "implId");
			return (Criteria) this;
		}

		public Criteria andImplIdNotEqualTo(BigDecimal value) {
			addCriterion("IMPL_ID <>", value, "implId");
			return (Criteria) this;
		}

		public Criteria andImplIdGreaterThan(BigDecimal value) {
			addCriterion("IMPL_ID >", value, "implId");
			return (Criteria) this;
		}

		public Criteria andImplIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("IMPL_ID >=", value, "implId");
			return (Criteria) this;
		}

		public Criteria andImplIdLessThan(BigDecimal value) {
			addCriterion("IMPL_ID <", value, "implId");
			return (Criteria) this;
		}

		public Criteria andImplIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("IMPL_ID <=", value, "implId");
			return (Criteria) this;
		}

		public Criteria andImplIdIn(List<BigDecimal> values) {
			addCriterion("IMPL_ID in", values, "implId");
			return (Criteria) this;
		}

		public Criteria andImplIdNotIn(List<BigDecimal> values) {
			addCriterion("IMPL_ID not in", values, "implId");
			return (Criteria) this;
		}

		public Criteria andImplIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("IMPL_ID between", value1, value2, "implId");
			return (Criteria) this;
		}

		public Criteria andImplIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("IMPL_ID not between", value1, value2, "implId");
			return (Criteria) this;
		}

		public Criteria andComIdIsNull() {
			addCriterion("COM_ID is null");
			return (Criteria) this;
		}

		public Criteria andComIdIsNotNull() {
			addCriterion("COM_ID is not null");
			return (Criteria) this;
		}

		public Criteria andComIdEqualTo(BigDecimal value) {
			addCriterion("COM_ID =", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotEqualTo(BigDecimal value) {
			addCriterion("COM_ID <>", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdGreaterThan(BigDecimal value) {
			addCriterion("COM_ID >", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("COM_ID >=", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdLessThan(BigDecimal value) {
			addCriterion("COM_ID <", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("COM_ID <=", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdIn(List<BigDecimal> values) {
			addCriterion("COM_ID in", values, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotIn(List<BigDecimal> values) {
			addCriterion("COM_ID not in", values, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COM_ID between", value1, value2, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COM_ID not between", value1, value2, "comId");
			return (Criteria) this;
		}

		public Criteria andBussIdIsNull() {
			addCriterion("BUSS_ID is null");
			return (Criteria) this;
		}

		public Criteria andBussIdIsNotNull() {
			addCriterion("BUSS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andBussIdEqualTo(BigDecimal value) {
			addCriterion("BUSS_ID =", value, "bussId");
			return (Criteria) this;
		}

		public Criteria andBussIdNotEqualTo(BigDecimal value) {
			addCriterion("BUSS_ID <>", value, "bussId");
			return (Criteria) this;
		}

		public Criteria andBussIdGreaterThan(BigDecimal value) {
			addCriterion("BUSS_ID >", value, "bussId");
			return (Criteria) this;
		}

		public Criteria andBussIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("BUSS_ID >=", value, "bussId");
			return (Criteria) this;
		}

		public Criteria andBussIdLessThan(BigDecimal value) {
			addCriterion("BUSS_ID <", value, "bussId");
			return (Criteria) this;
		}

		public Criteria andBussIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("BUSS_ID <=", value, "bussId");
			return (Criteria) this;
		}

		public Criteria andBussIdIn(List<BigDecimal> values) {
			addCriterion("BUSS_ID in", values, "bussId");
			return (Criteria) this;
		}

		public Criteria andBussIdNotIn(List<BigDecimal> values) {
			addCriterion("BUSS_ID not in", values, "bussId");
			return (Criteria) this;
		}

		public Criteria andBussIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("BUSS_ID between", value1, value2, "bussId");
			return (Criteria) this;
		}

		public Criteria andBussIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("BUSS_ID not between", value1, value2, "bussId");
			return (Criteria) this;
		}

		public Criteria andExcCodeIsNull() {
			addCriterion("EXC_CODE is null");
			return (Criteria) this;
		}

		public Criteria andExcCodeIsNotNull() {
			addCriterion("EXC_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andExcCodeEqualTo(String value) {
			addCriterion("EXC_CODE =", value, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeNotEqualTo(String value) {
			addCriterion("EXC_CODE <>", value, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeGreaterThan(String value) {
			addCriterion("EXC_CODE >", value, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeGreaterThanOrEqualTo(String value) {
			addCriterion("EXC_CODE >=", value, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeLessThan(String value) {
			addCriterion("EXC_CODE <", value, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeLessThanOrEqualTo(String value) {
			addCriterion("EXC_CODE <=", value, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeLike(String value) {
			addCriterion("EXC_CODE like", value, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeNotLike(String value) {
			addCriterion("EXC_CODE not like", value, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeIn(List<String> values) {
			addCriterion("EXC_CODE in", values, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeNotIn(List<String> values) {
			addCriterion("EXC_CODE not in", values, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeBetween(String value1, String value2) {
			addCriterion("EXC_CODE between", value1, value2, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcCodeNotBetween(String value1, String value2) {
			addCriterion("EXC_CODE not between", value1, value2, "excCode");
			return (Criteria) this;
		}

		public Criteria andExcNameIsNull() {
			addCriterion("EXC_NAME is null");
			return (Criteria) this;
		}

		public Criteria andExcNameIsNotNull() {
			addCriterion("EXC_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andExcNameEqualTo(String value) {
			addCriterion("EXC_NAME =", value, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameNotEqualTo(String value) {
			addCriterion("EXC_NAME <>", value, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameGreaterThan(String value) {
			addCriterion("EXC_NAME >", value, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameGreaterThanOrEqualTo(String value) {
			addCriterion("EXC_NAME >=", value, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameLessThan(String value) {
			addCriterion("EXC_NAME <", value, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameLessThanOrEqualTo(String value) {
			addCriterion("EXC_NAME <=", value, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameLike(String value) {
			addCriterion("EXC_NAME like", value, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameNotLike(String value) {
			addCriterion("EXC_NAME not like", value, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameIn(List<String> values) {
			addCriterion("EXC_NAME in", values, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameNotIn(List<String> values) {
			addCriterion("EXC_NAME not in", values, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameBetween(String value1, String value2) {
			addCriterion("EXC_NAME between", value1, value2, "excName");
			return (Criteria) this;
		}

		public Criteria andExcNameNotBetween(String value1, String value2) {
			addCriterion("EXC_NAME not between", value1, value2, "excName");
			return (Criteria) this;
		}

		public Criteria andExcDescIsNull() {
			addCriterion("EXC_DESC is null");
			return (Criteria) this;
		}

		public Criteria andExcDescIsNotNull() {
			addCriterion("EXC_DESC is not null");
			return (Criteria) this;
		}

		public Criteria andExcDescEqualTo(String value) {
			addCriterion("EXC_DESC =", value, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescNotEqualTo(String value) {
			addCriterion("EXC_DESC <>", value, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescGreaterThan(String value) {
			addCriterion("EXC_DESC >", value, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescGreaterThanOrEqualTo(String value) {
			addCriterion("EXC_DESC >=", value, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescLessThan(String value) {
			addCriterion("EXC_DESC <", value, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescLessThanOrEqualTo(String value) {
			addCriterion("EXC_DESC <=", value, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescLike(String value) {
			addCriterion("EXC_DESC like", value, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescNotLike(String value) {
			addCriterion("EXC_DESC not like", value, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescIn(List<String> values) {
			addCriterion("EXC_DESC in", values, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescNotIn(List<String> values) {
			addCriterion("EXC_DESC not in", values, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescBetween(String value1, String value2) {
			addCriterion("EXC_DESC between", value1, value2, "excDesc");
			return (Criteria) this;
		}

		public Criteria andExcDescNotBetween(String value1, String value2) {
			addCriterion("EXC_DESC not between", value1, value2, "excDesc");
			return (Criteria) this;
		}

		public Criteria andRcStatusIsNull() {
			addCriterion("RC_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andRcStatusIsNotNull() {
			addCriterion("RC_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andRcStatusEqualTo(Short value) {
			addCriterion("RC_STATUS =", value, "rcStatus");
			return (Criteria) this;
		}

		public Criteria andRcStatusNotEqualTo(Short value) {
			addCriterion("RC_STATUS <>", value, "rcStatus");
			return (Criteria) this;
		}

		public Criteria andRcStatusGreaterThan(Short value) {
			addCriterion("RC_STATUS >", value, "rcStatus");
			return (Criteria) this;
		}

		public Criteria andRcStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("RC_STATUS >=", value, "rcStatus");
			return (Criteria) this;
		}

		public Criteria andRcStatusLessThan(Short value) {
			addCriterion("RC_STATUS <", value, "rcStatus");
			return (Criteria) this;
		}

		public Criteria andRcStatusLessThanOrEqualTo(Short value) {
			addCriterion("RC_STATUS <=", value, "rcStatus");
			return (Criteria) this;
		}

		public Criteria andRcStatusIn(List<Short> values) {
			addCriterion("RC_STATUS in", values, "rcStatus");
			return (Criteria) this;
		}

		public Criteria andRcStatusNotIn(List<Short> values) {
			addCriterion("RC_STATUS not in", values, "rcStatus");
			return (Criteria) this;
		}

		public Criteria andRcStatusBetween(Short value1, Short value2) {
			addCriterion("RC_STATUS between", value1, value2, "rcStatus");
			return (Criteria) this;
		}

		public Criteria andRcStatusNotBetween(Short value1, Short value2) {
			addCriterion("RC_STATUS not between", value1, value2, "rcStatus");
			return (Criteria) this;
		}

		public Criteria andInsertTimeIsNull() {
			addCriterion("INSERT_TIME is null");
			return (Criteria) this;
		}

		public Criteria andInsertTimeIsNotNull() {
			addCriterion("INSERT_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andInsertTimeEqualTo(Date value) {
			addCriterionForJDBCDate("INSERT_TIME =", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("INSERT_TIME <>", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("INSERT_TIME >", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("INSERT_TIME >=", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeLessThan(Date value) {
			addCriterionForJDBCDate("INSERT_TIME <", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("INSERT_TIME <=", value, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeIn(List<Date> values) {
			addCriterionForJDBCDate("INSERT_TIME in", values, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("INSERT_TIME not in", values, "insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("INSERT_TIME between", value1, value2,
					"insertTime");
			return (Criteria) this;
		}

		public Criteria andInsertTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("INSERT_TIME not between", value1, value2,
					"insertTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeIsNull() {
			addCriterion("LAST_MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeIsNotNull() {
			addCriterion("LAST_MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME =", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME <>", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME >", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME >=", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeLessThan(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME <", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME <=", value,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeIn(List<Date> values) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME in", values,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME not in", values,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME between", value1, value2,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_MODIFY_TIME not between", value1,
					value2, "lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andOperatorIsNull() {
			addCriterion("OPERATOR is null");
			return (Criteria) this;
		}

		public Criteria andOperatorIsNotNull() {
			addCriterion("OPERATOR is not null");
			return (Criteria) this;
		}

		public Criteria andOperatorEqualTo(String value) {
			addCriterion("OPERATOR =", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotEqualTo(String value) {
			addCriterion("OPERATOR <>", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorGreaterThan(String value) {
			addCriterion("OPERATOR >", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATOR >=", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorLessThan(String value) {
			addCriterion("OPERATOR <", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorLessThanOrEqualTo(String value) {
			addCriterion("OPERATOR <=", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorLike(String value) {
			addCriterion("OPERATOR like", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotLike(String value) {
			addCriterion("OPERATOR not like", value, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorIn(List<String> values) {
			addCriterion("OPERATOR in", values, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotIn(List<String> values) {
			addCriterion("OPERATOR not in", values, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorBetween(String value1, String value2) {
			addCriterion("OPERATOR between", value1, value2, "operator");
			return (Criteria) this;
		}

		public Criteria andOperatorNotBetween(String value1, String value2) {
			addCriterion("OPERATOR not between", value1, value2, "operator");
			return (Criteria) this;
		}

		public Criteria andExcNumIsNull() {
			addCriterion("EXC_NUM is null");
			return (Criteria) this;
		}

		public Criteria andExcNumIsNotNull() {
			addCriterion("EXC_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andExcNumEqualTo(Short value) {
			addCriterion("EXC_NUM =", value, "excNum");
			return (Criteria) this;
		}

		public Criteria andExcNumNotEqualTo(Short value) {
			addCriterion("EXC_NUM <>", value, "excNum");
			return (Criteria) this;
		}

		public Criteria andExcNumGreaterThan(Short value) {
			addCriterion("EXC_NUM >", value, "excNum");
			return (Criteria) this;
		}

		public Criteria andExcNumGreaterThanOrEqualTo(Short value) {
			addCriterion("EXC_NUM >=", value, "excNum");
			return (Criteria) this;
		}

		public Criteria andExcNumLessThan(Short value) {
			addCriterion("EXC_NUM <", value, "excNum");
			return (Criteria) this;
		}

		public Criteria andExcNumLessThanOrEqualTo(Short value) {
			addCriterion("EXC_NUM <=", value, "excNum");
			return (Criteria) this;
		}

		public Criteria andExcNumIn(List<Short> values) {
			addCriterion("EXC_NUM in", values, "excNum");
			return (Criteria) this;
		}

		public Criteria andExcNumNotIn(List<Short> values) {
			addCriterion("EXC_NUM not in", values, "excNum");
			return (Criteria) this;
		}

		public Criteria andExcNumBetween(Short value1, Short value2) {
			addCriterion("EXC_NUM between", value1, value2, "excNum");
			return (Criteria) this;
		}

		public Criteria andExcNumNotBetween(Short value1, Short value2) {
			addCriterion("EXC_NUM not between", value1, value2, "excNum");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table T_DEF_TRANSEXC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_DEF_TRANSEXC
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 28 10:23:43 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}