package com.sinosoft.ummp.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class TDefActionReturn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.ID
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.ACTION_NO
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String actionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.PLAT_COM
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private BigDecimal platCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.BUSS_TYPE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String bussType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.SUB_BUSS_TYPE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String subBussType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.DATA_STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.CHECK_STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.QUERY_NO
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String queryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.RETURN_MSG
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String returnMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.ERRO_RATIO
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private BigDecimal erroRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.ERR_INFO_PATH
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String errInfoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.RETURN_CODE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.DATA_TYPE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.DATA_FLAG
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String dataFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.OPERATOR
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.INSERT_TIME
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.LAST_MODIFY_TIME
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.ES_STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private Short esStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.STANDBY1
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String standby1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.STANDBY2
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String standby2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.STANDBY3
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String standby3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.STANDBY4
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String standby4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_ACTION_RETURN.RETURN_DATA
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    private String returnData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.ID
     *
     * @return the value of T_DEF_ACTION_RETURN.ID
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.ID
     *
     * @param id the value for T_DEF_ACTION_RETURN.ID
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.ACTION_NO
     *
     * @return the value of T_DEF_ACTION_RETURN.ACTION_NO
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getActionNo() {
        return actionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.ACTION_NO
     *
     * @param actionNo the value for T_DEF_ACTION_RETURN.ACTION_NO
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setActionNo(String actionNo) {
        this.actionNo = actionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.PLAT_COM
     *
     * @return the value of T_DEF_ACTION_RETURN.PLAT_COM
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public BigDecimal getPlatCom() {
        return platCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.PLAT_COM
     *
     * @param platCom the value for T_DEF_ACTION_RETURN.PLAT_COM
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setPlatCom(BigDecimal platCom) {
        this.platCom = platCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.BUSS_TYPE
     *
     * @return the value of T_DEF_ACTION_RETURN.BUSS_TYPE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getBussType() {
        return bussType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.BUSS_TYPE
     *
     * @param bussType the value for T_DEF_ACTION_RETURN.BUSS_TYPE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setBussType(String bussType) {
        this.bussType = bussType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.SUB_BUSS_TYPE
     *
     * @return the value of T_DEF_ACTION_RETURN.SUB_BUSS_TYPE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getSubBussType() {
        return subBussType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.SUB_BUSS_TYPE
     *
     * @param subBussType the value for T_DEF_ACTION_RETURN.SUB_BUSS_TYPE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setSubBussType(String subBussType) {
        this.subBussType = subBussType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.STATUS
     *
     * @return the value of T_DEF_ACTION_RETURN.STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.STATUS
     *
     * @param status the value for T_DEF_ACTION_RETURN.STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.DATA_STATUS
     *
     * @return the value of T_DEF_ACTION_RETURN.DATA_STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.DATA_STATUS
     *
     * @param dataStatus the value for T_DEF_ACTION_RETURN.DATA_STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.CHECK_STATUS
     *
     * @return the value of T_DEF_ACTION_RETURN.CHECK_STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.CHECK_STATUS
     *
     * @param checkStatus the value for T_DEF_ACTION_RETURN.CHECK_STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.QUERY_NO
     *
     * @return the value of T_DEF_ACTION_RETURN.QUERY_NO
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getQueryNo() {
        return queryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.QUERY_NO
     *
     * @param queryNo the value for T_DEF_ACTION_RETURN.QUERY_NO
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setQueryNo(String queryNo) {
        this.queryNo = queryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.RETURN_MSG
     *
     * @return the value of T_DEF_ACTION_RETURN.RETURN_MSG
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.RETURN_MSG
     *
     * @param returnMsg the value for T_DEF_ACTION_RETURN.RETURN_MSG
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.ERRO_RATIO
     *
     * @return the value of T_DEF_ACTION_RETURN.ERRO_RATIO
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public BigDecimal getErroRatio() {
        return erroRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.ERRO_RATIO
     *
     * @param erroRatio the value for T_DEF_ACTION_RETURN.ERRO_RATIO
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setErroRatio(BigDecimal erroRatio) {
        this.erroRatio = erroRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.ERR_INFO_PATH
     *
     * @return the value of T_DEF_ACTION_RETURN.ERR_INFO_PATH
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getErrInfoPath() {
        return errInfoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.ERR_INFO_PATH
     *
     * @param errInfoPath the value for T_DEF_ACTION_RETURN.ERR_INFO_PATH
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setErrInfoPath(String errInfoPath) {
        this.errInfoPath = errInfoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.RETURN_CODE
     *
     * @return the value of T_DEF_ACTION_RETURN.RETURN_CODE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.RETURN_CODE
     *
     * @param returnCode the value for T_DEF_ACTION_RETURN.RETURN_CODE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.DATA_TYPE
     *
     * @return the value of T_DEF_ACTION_RETURN.DATA_TYPE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.DATA_TYPE
     *
     * @param dataType the value for T_DEF_ACTION_RETURN.DATA_TYPE
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.DATA_FLAG
     *
     * @return the value of T_DEF_ACTION_RETURN.DATA_FLAG
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.DATA_FLAG
     *
     * @param dataFlag the value for T_DEF_ACTION_RETURN.DATA_FLAG
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.OPERATOR
     *
     * @return the value of T_DEF_ACTION_RETURN.OPERATOR
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.OPERATOR
     *
     * @param operator the value for T_DEF_ACTION_RETURN.OPERATOR
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.INSERT_TIME
     *
     * @return the value of T_DEF_ACTION_RETURN.INSERT_TIME
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.INSERT_TIME
     *
     * @param insertTime the value for T_DEF_ACTION_RETURN.INSERT_TIME
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.LAST_MODIFY_TIME
     *
     * @return the value of T_DEF_ACTION_RETURN.LAST_MODIFY_TIME
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for T_DEF_ACTION_RETURN.LAST_MODIFY_TIME
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.ES_STATUS
     *
     * @return the value of T_DEF_ACTION_RETURN.ES_STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public Short getEsStatus() {
        return esStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.ES_STATUS
     *
     * @param esStatus the value for T_DEF_ACTION_RETURN.ES_STATUS
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setEsStatus(Short esStatus) {
        this.esStatus = esStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.STANDBY1
     *
     * @return the value of T_DEF_ACTION_RETURN.STANDBY1
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getStandby1() {
        return standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.STANDBY1
     *
     * @param standby1 the value for T_DEF_ACTION_RETURN.STANDBY1
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setStandby1(String standby1) {
        this.standby1 = standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.STANDBY2
     *
     * @return the value of T_DEF_ACTION_RETURN.STANDBY2
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getStandby2() {
        return standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.STANDBY2
     *
     * @param standby2 the value for T_DEF_ACTION_RETURN.STANDBY2
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setStandby2(String standby2) {
        this.standby2 = standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.STANDBY3
     *
     * @return the value of T_DEF_ACTION_RETURN.STANDBY3
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getStandby3() {
        return standby3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.STANDBY3
     *
     * @param standby3 the value for T_DEF_ACTION_RETURN.STANDBY3
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setStandby3(String standby3) {
        this.standby3 = standby3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.STANDBY4
     *
     * @return the value of T_DEF_ACTION_RETURN.STANDBY4
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getStandby4() {
        return standby4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.STANDBY4
     *
     * @param standby4 the value for T_DEF_ACTION_RETURN.STANDBY4
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setStandby4(String standby4) {
        this.standby4 = standby4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_ACTION_RETURN.RETURN_DATA
     *
     * @return the value of T_DEF_ACTION_RETURN.RETURN_DATA
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public String getReturnData() {
        return returnData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_ACTION_RETURN.RETURN_DATA
     *
     * @param returnData the value for T_DEF_ACTION_RETURN.RETURN_DATA
     *
     * @mbggenerated Mon Aug 29 14:40:55 CST 2016
     */
    public void setReturnData(String returnData) {
        this.returnData = returnData;
    }
}