package com.sinosoft.ummp.domain.model;

import java.math.BigDecimal;

public class TDefWSPRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_WSP_REQUEST.ID
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_WSP_REQUEST.COM_ID
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    private BigDecimal comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_WSP_REQUEST.REQUEST_METHOD
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    private String requestMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_WSP_REQUEST.REQUEST_NAME
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    private String requestName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_WSP_REQUEST.REQUEST_CLASS
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    private String requestClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_WSP_REQUEST.REQUEST_TYPE
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    private String requestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_WSP_REQUEST.BUSS_TYPE
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    private String bussType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_WSP_REQUEST.ES_STATUS
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    private Short esStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_WSP_REQUEST.ID
     *
     * @return the value of T_DEF_WSP_REQUEST.ID
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_WSP_REQUEST.ID
     *
     * @param id the value for T_DEF_WSP_REQUEST.ID
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_WSP_REQUEST.COM_ID
     *
     * @return the value of T_DEF_WSP_REQUEST.COM_ID
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public BigDecimal getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_WSP_REQUEST.COM_ID
     *
     * @param comId the value for T_DEF_WSP_REQUEST.COM_ID
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public void setComId(BigDecimal comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_WSP_REQUEST.REQUEST_METHOD
     *
     * @return the value of T_DEF_WSP_REQUEST.REQUEST_METHOD
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_WSP_REQUEST.REQUEST_METHOD
     *
     * @param requestMethod the value for T_DEF_WSP_REQUEST.REQUEST_METHOD
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_WSP_REQUEST.REQUEST_NAME
     *
     * @return the value of T_DEF_WSP_REQUEST.REQUEST_NAME
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public String getRequestName() {
        return requestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_WSP_REQUEST.REQUEST_NAME
     *
     * @param requestName the value for T_DEF_WSP_REQUEST.REQUEST_NAME
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public void setRequestName(String requestName) {
        this.requestName = requestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_WSP_REQUEST.REQUEST_CLASS
     *
     * @return the value of T_DEF_WSP_REQUEST.REQUEST_CLASS
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public String getRequestClass() {
        return requestClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_WSP_REQUEST.REQUEST_CLASS
     *
     * @param requestClass the value for T_DEF_WSP_REQUEST.REQUEST_CLASS
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public void setRequestClass(String requestClass) {
        this.requestClass = requestClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_WSP_REQUEST.REQUEST_TYPE
     *
     * @return the value of T_DEF_WSP_REQUEST.REQUEST_TYPE
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_WSP_REQUEST.REQUEST_TYPE
     *
     * @param requestType the value for T_DEF_WSP_REQUEST.REQUEST_TYPE
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_WSP_REQUEST.BUSS_TYPE
     *
     * @return the value of T_DEF_WSP_REQUEST.BUSS_TYPE
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public String getBussType() {
        return bussType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_WSP_REQUEST.BUSS_TYPE
     *
     * @param bussType the value for T_DEF_WSP_REQUEST.BUSS_TYPE
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public void setBussType(String bussType) {
        this.bussType = bussType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_WSP_REQUEST.ES_STATUS
     *
     * @return the value of T_DEF_WSP_REQUEST.ES_STATUS
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public Short getEsStatus() {
        return esStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_WSP_REQUEST.ES_STATUS
     *
     * @param esStatus the value for T_DEF_WSP_REQUEST.ES_STATUS
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    public void setEsStatus(Short esStatus) {
        this.esStatus = esStatus;
    }
}