package com.sinosoft.ummp.domain.model;

import java.math.BigDecimal;

public class TDefNoticeMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_NOTICE_MAIN.ID
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_NOTICE_MAIN.NOTICE_ID
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    private BigDecimal noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_NOTICE_MAIN.NOTICE_TO
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    private String noticeTo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_NOTICE_MAIN.ID
     *
     * @return the value of T_DEF_NOTICE_MAIN.ID
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_NOTICE_MAIN.ID
     *
     * @param id the value for T_DEF_NOTICE_MAIN.ID
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_NOTICE_MAIN.NOTICE_ID
     *
     * @return the value of T_DEF_NOTICE_MAIN.NOTICE_ID
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    public BigDecimal getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_NOTICE_MAIN.NOTICE_ID
     *
     * @param noticeId the value for T_DEF_NOTICE_MAIN.NOTICE_ID
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    public void setNoticeId(BigDecimal noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_NOTICE_MAIN.NOTICE_TO
     *
     * @return the value of T_DEF_NOTICE_MAIN.NOTICE_TO
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    public String getNoticeTo() {
        return noticeTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_NOTICE_MAIN.NOTICE_TO
     *
     * @param noticeTo the value for T_DEF_NOTICE_MAIN.NOTICE_TO
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    public void setNoticeTo(String noticeTo) {
        this.noticeTo = noticeTo;
    }
}