package com.sinosoft.ummp.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class TDefTransexc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.EXC_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private BigDecimal excId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.IMPL_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private BigDecimal implId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.COM_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private BigDecimal comId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.BUSS_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private BigDecimal bussId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.EXC_CODE
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private String excCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.EXC_NAME
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private String excName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.EXC_DESC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private String excDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.RC_STATUS
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private Short rcStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.INSERT_TIME
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private Date insertTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.LAST_MODIFY_TIME
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private Date lastModifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.OPERATOR
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DEF_TRANSEXC.EXC_NUM
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	private Short excNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.EXC_ID
	 * @return  the value of T_DEF_TRANSEXC.EXC_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public BigDecimal getExcId() {
		return excId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.EXC_ID
	 * @param excId  the value for T_DEF_TRANSEXC.EXC_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setExcId(BigDecimal excId) {
		this.excId = excId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.IMPL_ID
	 * @return  the value of T_DEF_TRANSEXC.IMPL_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public BigDecimal getImplId() {
		return implId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.IMPL_ID
	 * @param implId  the value for T_DEF_TRANSEXC.IMPL_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setImplId(BigDecimal implId) {
		this.implId = implId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.COM_ID
	 * @return  the value of T_DEF_TRANSEXC.COM_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public BigDecimal getComId() {
		return comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.COM_ID
	 * @param comId  the value for T_DEF_TRANSEXC.COM_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setComId(BigDecimal comId) {
		this.comId = comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.BUSS_ID
	 * @return  the value of T_DEF_TRANSEXC.BUSS_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public BigDecimal getBussId() {
		return bussId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.BUSS_ID
	 * @param bussId  the value for T_DEF_TRANSEXC.BUSS_ID
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setBussId(BigDecimal bussId) {
		this.bussId = bussId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.EXC_CODE
	 * @return  the value of T_DEF_TRANSEXC.EXC_CODE
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public String getExcCode() {
		return excCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.EXC_CODE
	 * @param excCode  the value for T_DEF_TRANSEXC.EXC_CODE
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setExcCode(String excCode) {
		this.excCode = excCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.EXC_NAME
	 * @return  the value of T_DEF_TRANSEXC.EXC_NAME
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public String getExcName() {
		return excName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.EXC_NAME
	 * @param excName  the value for T_DEF_TRANSEXC.EXC_NAME
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setExcName(String excName) {
		this.excName = excName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.EXC_DESC
	 * @return  the value of T_DEF_TRANSEXC.EXC_DESC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public String getExcDesc() {
		return excDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.EXC_DESC
	 * @param excDesc  the value for T_DEF_TRANSEXC.EXC_DESC
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setExcDesc(String excDesc) {
		this.excDesc = excDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.RC_STATUS
	 * @return  the value of T_DEF_TRANSEXC.RC_STATUS
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public Short getRcStatus() {
		return rcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.RC_STATUS
	 * @param rcStatus  the value for T_DEF_TRANSEXC.RC_STATUS
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setRcStatus(Short rcStatus) {
		this.rcStatus = rcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.INSERT_TIME
	 * @return  the value of T_DEF_TRANSEXC.INSERT_TIME
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.INSERT_TIME
	 * @param insertTime  the value for T_DEF_TRANSEXC.INSERT_TIME
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.LAST_MODIFY_TIME
	 * @return  the value of T_DEF_TRANSEXC.LAST_MODIFY_TIME
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public Date getLastModifyTime() {
		return lastModifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.LAST_MODIFY_TIME
	 * @param lastModifyTime  the value for T_DEF_TRANSEXC.LAST_MODIFY_TIME
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setLastModifyTime(Date lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.OPERATOR
	 * @return  the value of T_DEF_TRANSEXC.OPERATOR
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.OPERATOR
	 * @param operator  the value for T_DEF_TRANSEXC.OPERATOR
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DEF_TRANSEXC.EXC_NUM
	 * @return  the value of T_DEF_TRANSEXC.EXC_NUM
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public Short getExcNum() {
		return excNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DEF_TRANSEXC.EXC_NUM
	 * @param excNum  the value for T_DEF_TRANSEXC.EXC_NUM
	 * @mbggenerated  Thu Sep 01 11:09:07 CST 2016
	 */
	public void setExcNum(Short excNum) {
		this.excNum = excNum;
	}
}