package com.sinosoft.ummp.domain.model;

import java.math.BigDecimal;

public class TDefSend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.ID
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.COM_ID
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private BigDecimal comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.SEND_TYPE
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private String sendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.SEND_ENCODE
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private String sendEncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.SEND_USER
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private String sendUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.SEND_PASS
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private String sendPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.SEND_API
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private String sendApi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.SEND_IP
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private String sendIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.SEND_PORT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private String sendPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.MAX_COUNT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private Integer maxCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.MIN_COUNT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private Integer minCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEF_SEND.BATCH_COUNT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    private Integer batchCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.ID
     *
     * @return the value of T_DEF_SEND.ID
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.ID
     *
     * @param id the value for T_DEF_SEND.ID
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.COM_ID
     *
     * @return the value of T_DEF_SEND.COM_ID
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public BigDecimal getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.COM_ID
     *
     * @param comId the value for T_DEF_SEND.COM_ID
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setComId(BigDecimal comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.SEND_TYPE
     *
     * @return the value of T_DEF_SEND.SEND_TYPE
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public String getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.SEND_TYPE
     *
     * @param sendType the value for T_DEF_SEND.SEND_TYPE
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setSendType(String sendType) {
        this.sendType = sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.SEND_ENCODE
     *
     * @return the value of T_DEF_SEND.SEND_ENCODE
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public String getSendEncode() {
        return sendEncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.SEND_ENCODE
     *
     * @param sendEncode the value for T_DEF_SEND.SEND_ENCODE
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setSendEncode(String sendEncode) {
        this.sendEncode = sendEncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.SEND_USER
     *
     * @return the value of T_DEF_SEND.SEND_USER
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public String getSendUser() {
        return sendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.SEND_USER
     *
     * @param sendUser the value for T_DEF_SEND.SEND_USER
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setSendUser(String sendUser) {
        this.sendUser = sendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.SEND_PASS
     *
     * @return the value of T_DEF_SEND.SEND_PASS
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public String getSendPass() {
        return sendPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.SEND_PASS
     *
     * @param sendPass the value for T_DEF_SEND.SEND_PASS
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setSendPass(String sendPass) {
        this.sendPass = sendPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.SEND_API
     *
     * @return the value of T_DEF_SEND.SEND_API
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public String getSendApi() {
        return sendApi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.SEND_API
     *
     * @param sendApi the value for T_DEF_SEND.SEND_API
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setSendApi(String sendApi) {
        this.sendApi = sendApi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.SEND_IP
     *
     * @return the value of T_DEF_SEND.SEND_IP
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public String getSendIp() {
        return sendIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.SEND_IP
     *
     * @param sendIp the value for T_DEF_SEND.SEND_IP
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setSendIp(String sendIp) {
        this.sendIp = sendIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.SEND_PORT
     *
     * @return the value of T_DEF_SEND.SEND_PORT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public String getSendPort() {
        return sendPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.SEND_PORT
     *
     * @param sendPort the value for T_DEF_SEND.SEND_PORT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setSendPort(String sendPort) {
        this.sendPort = sendPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.MAX_COUNT
     *
     * @return the value of T_DEF_SEND.MAX_COUNT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public Integer getMaxCount() {
        return maxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.MAX_COUNT
     *
     * @param maxCount the value for T_DEF_SEND.MAX_COUNT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setMaxCount(Integer maxCount) {
        this.maxCount = maxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.MIN_COUNT
     *
     * @return the value of T_DEF_SEND.MIN_COUNT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public Integer getMinCount() {
        return minCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.MIN_COUNT
     *
     * @param minCount the value for T_DEF_SEND.MIN_COUNT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setMinCount(Integer minCount) {
        this.minCount = minCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEF_SEND.BATCH_COUNT
     *
     * @return the value of T_DEF_SEND.BATCH_COUNT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public Integer getBatchCount() {
        return batchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEF_SEND.BATCH_COUNT
     *
     * @param batchCount the value for T_DEF_SEND.BATCH_COUNT
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    public void setBatchCount(Integer batchCount) {
        this.batchCount = batchCount;
    }
}