package com.sinosoft.ummp.domain.model;

public class TDocUpdownKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DOC_UPDOWN.DOC_NAME
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    private String docName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DOC_UPDOWN.DOC_TYPE
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    private String docType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DOC_UPDOWN.DOC_SUFFIX
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    private String docSuffix;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DOC_UPDOWN.DOC_NAME
     *
     * @return the value of T_DOC_UPDOWN.DOC_NAME
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    public String getDocName() {
        return docName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DOC_UPDOWN.DOC_NAME
     *
     * @param docName the value for T_DOC_UPDOWN.DOC_NAME
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    public void setDocName(String docName) {
        this.docName = docName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DOC_UPDOWN.DOC_TYPE
     *
     * @return the value of T_DOC_UPDOWN.DOC_TYPE
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    public String getDocType() {
        return docType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DOC_UPDOWN.DOC_TYPE
     *
     * @param docType the value for T_DOC_UPDOWN.DOC_TYPE
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    public void setDocType(String docType) {
        this.docType = docType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DOC_UPDOWN.DOC_SUFFIX
     *
     * @return the value of T_DOC_UPDOWN.DOC_SUFFIX
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    public String getDocSuffix() {
        return docSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DOC_UPDOWN.DOC_SUFFIX
     *
     * @param docSuffix the value for T_DOC_UPDOWN.DOC_SUFFIX
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    public void setDocSuffix(String docSuffix) {
        this.docSuffix = docSuffix;
    }
}