package com.sinosoft.ummp.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class TDocMain {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.DOC_ID
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private BigDecimal docId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.BATCH_NO
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String batchNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.TRANS_NO
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String transNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.DOC_CODE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String docCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.DOC_UNIC
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String docUnic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.BUSS_TYPE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String bussType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.SUB_BUSS_TYPE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String subBussType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.DOC_PAGES
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private BigDecimal docPages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.ACTION_TIMES
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private BigDecimal actionTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.DOC_FLAG
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String docFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.DOC_REMARK
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String docRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.COM_ID
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String comId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.ES_STATUS
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private Short esStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.SCAN_OPERATOR
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String scanOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.INSERT_TIME
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private Date insertTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.LAST_MODIFY_TIME
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private Date lastModifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.OPERATOR
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.VERSION
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.PRINT_CODE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String printCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_DOC_MAIN.ACTION_FLAG
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	private String actionFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.DOC_ID
	 * @return  the value of T_DOC_MAIN.DOC_ID
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public BigDecimal getDocId() {
		return docId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.DOC_ID
	 * @param docId  the value for T_DOC_MAIN.DOC_ID
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setDocId(BigDecimal docId) {
		this.docId = docId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.BATCH_NO
	 * @return  the value of T_DOC_MAIN.BATCH_NO
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getBatchNo() {
		return batchNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.BATCH_NO
	 * @param batchNo  the value for T_DOC_MAIN.BATCH_NO
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.TRANS_NO
	 * @return  the value of T_DOC_MAIN.TRANS_NO
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getTransNo() {
		return transNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.TRANS_NO
	 * @param transNo  the value for T_DOC_MAIN.TRANS_NO
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setTransNo(String transNo) {
		this.transNo = transNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.DOC_CODE
	 * @return  the value of T_DOC_MAIN.DOC_CODE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getDocCode() {
		return docCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.DOC_CODE
	 * @param docCode  the value for T_DOC_MAIN.DOC_CODE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setDocCode(String docCode) {
		this.docCode = docCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.DOC_UNIC
	 * @return  the value of T_DOC_MAIN.DOC_UNIC
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getDocUnic() {
		return docUnic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.DOC_UNIC
	 * @param docUnic  the value for T_DOC_MAIN.DOC_UNIC
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setDocUnic(String docUnic) {
		this.docUnic = docUnic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.BUSS_TYPE
	 * @return  the value of T_DOC_MAIN.BUSS_TYPE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getBussType() {
		return bussType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.BUSS_TYPE
	 * @param bussType  the value for T_DOC_MAIN.BUSS_TYPE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setBussType(String bussType) {
		this.bussType = bussType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.SUB_BUSS_TYPE
	 * @return  the value of T_DOC_MAIN.SUB_BUSS_TYPE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getSubBussType() {
		return subBussType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.SUB_BUSS_TYPE
	 * @param subBussType  the value for T_DOC_MAIN.SUB_BUSS_TYPE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setSubBussType(String subBussType) {
		this.subBussType = subBussType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.DOC_PAGES
	 * @return  the value of T_DOC_MAIN.DOC_PAGES
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public BigDecimal getDocPages() {
		return docPages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.DOC_PAGES
	 * @param docPages  the value for T_DOC_MAIN.DOC_PAGES
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setDocPages(BigDecimal docPages) {
		this.docPages = docPages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.ACTION_TIMES
	 * @return  the value of T_DOC_MAIN.ACTION_TIMES
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public BigDecimal getActionTimes() {
		return actionTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.ACTION_TIMES
	 * @param actionTimes  the value for T_DOC_MAIN.ACTION_TIMES
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setActionTimes(BigDecimal actionTimes) {
		this.actionTimes = actionTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.DOC_FLAG
	 * @return  the value of T_DOC_MAIN.DOC_FLAG
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getDocFlag() {
		return docFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.DOC_FLAG
	 * @param docFlag  the value for T_DOC_MAIN.DOC_FLAG
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setDocFlag(String docFlag) {
		this.docFlag = docFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.DOC_REMARK
	 * @return  the value of T_DOC_MAIN.DOC_REMARK
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getDocRemark() {
		return docRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.DOC_REMARK
	 * @param docRemark  the value for T_DOC_MAIN.DOC_REMARK
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setDocRemark(String docRemark) {
		this.docRemark = docRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.COM_ID
	 * @return  the value of T_DOC_MAIN.COM_ID
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getComId() {
		return comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.COM_ID
	 * @param comId  the value for T_DOC_MAIN.COM_ID
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setComId(String comId) {
		this.comId = comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.ES_STATUS
	 * @return  the value of T_DOC_MAIN.ES_STATUS
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public Short getEsStatus() {
		return esStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.ES_STATUS
	 * @param esStatus  the value for T_DOC_MAIN.ES_STATUS
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setEsStatus(Short esStatus) {
		this.esStatus = esStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.SCAN_OPERATOR
	 * @return  the value of T_DOC_MAIN.SCAN_OPERATOR
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getScanOperator() {
		return scanOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.SCAN_OPERATOR
	 * @param scanOperator  the value for T_DOC_MAIN.SCAN_OPERATOR
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setScanOperator(String scanOperator) {
		this.scanOperator = scanOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.INSERT_TIME
	 * @return  the value of T_DOC_MAIN.INSERT_TIME
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.INSERT_TIME
	 * @param insertTime  the value for T_DOC_MAIN.INSERT_TIME
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.LAST_MODIFY_TIME
	 * @return  the value of T_DOC_MAIN.LAST_MODIFY_TIME
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public Date getLastModifyTime() {
		return lastModifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.LAST_MODIFY_TIME
	 * @param lastModifyTime  the value for T_DOC_MAIN.LAST_MODIFY_TIME
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setLastModifyTime(Date lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.OPERATOR
	 * @return  the value of T_DOC_MAIN.OPERATOR
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.OPERATOR
	 * @param operator  the value for T_DOC_MAIN.OPERATOR
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.VERSION
	 * @return  the value of T_DOC_MAIN.VERSION
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.VERSION
	 * @param version  the value for T_DOC_MAIN.VERSION
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.PRINT_CODE
	 * @return  the value of T_DOC_MAIN.PRINT_CODE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getPrintCode() {
		return printCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.PRINT_CODE
	 * @param printCode  the value for T_DOC_MAIN.PRINT_CODE
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setPrintCode(String printCode) {
		this.printCode = printCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_DOC_MAIN.ACTION_FLAG
	 * @return  the value of T_DOC_MAIN.ACTION_FLAG
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public String getActionFlag() {
		return actionFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_DOC_MAIN.ACTION_FLAG
	 * @param actionFlag  the value for T_DOC_MAIN.ACTION_FLAG
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	public void setActionFlag(String actionFlag) {
		this.actionFlag = actionFlag;
	}
}