package com.sinosoft.ummp.domain.model;

public class TPrpLcpreservationperiodKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRP_LCPRESERVATIONPERIOD.ID
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRP_LCPRESERVATIONPERIOD.YEAR
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    private String year;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRP_LCPRESERVATIONPERIOD.ID
     *
     * @return the value of T_PRP_LCPRESERVATIONPERIOD.ID
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRP_LCPRESERVATIONPERIOD.ID
     *
     * @param id the value for T_PRP_LCPRESERVATIONPERIOD.ID
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRP_LCPRESERVATIONPERIOD.YEAR
     *
     * @return the value of T_PRP_LCPRESERVATIONPERIOD.YEAR
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRP_LCPRESERVATIONPERIOD.YEAR
     *
     * @param year the value for T_PRP_LCPRESERVATIONPERIOD.YEAR
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    public void setYear(String year) {
        this.year = year;
    }
}