package com.sinosoft.ummp.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class TShiaSynchroRiskInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.ID
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.REQUEST_TYPE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String requestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.TASK_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String taskNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.RESPONSE_CODE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String responseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.ERROR_MESSAGE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String errorMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.POLICY_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String policySequenceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.UNDERWRIT_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String underwritSequenceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.CUTOMER_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String cutomerSequenceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.START_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.END_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_LIFE_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private BigDecimal allLifeSumInsured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_ACCIDENT_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private BigDecimal allAccidentSumInsured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_HEALTH_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private BigDecimal allHealthSumInsured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_OLD_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private BigDecimal allOldSumInsured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_OTHER_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private BigDecimal allOtherSumInsured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_HOSPITAL_ALLOWANCE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private BigDecimal allHospitalAllowance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_CLAIM_AMOUNT
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private BigDecimal allClaimAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.INSERT_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.LAST_MODIFY_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.OPERATOR
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.CLAIM_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String claimSequenceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.CUSTOMER_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String customerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHIA_SYNCHRO_RISK_INFO.RISK_TYPE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    private String riskType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ID
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.ID
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ID
     *
     * @param id the value for T_SHIA_SYNCHRO_RISK_INFO.ID
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.REQUEST_TYPE
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.REQUEST_TYPE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.REQUEST_TYPE
     *
     * @param requestType the value for T_SHIA_SYNCHRO_RISK_INFO.REQUEST_TYPE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.TASK_NO
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.TASK_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getTaskNo() {
        return taskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.TASK_NO
     *
     * @param taskNo the value for T_SHIA_SYNCHRO_RISK_INFO.TASK_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setTaskNo(String taskNo) {
        this.taskNo = taskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.RESPONSE_CODE
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.RESPONSE_CODE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.RESPONSE_CODE
     *
     * @param responseCode the value for T_SHIA_SYNCHRO_RISK_INFO.RESPONSE_CODE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setResponseCode(String responseCode) {
        this.responseCode = responseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ERROR_MESSAGE
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.ERROR_MESSAGE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ERROR_MESSAGE
     *
     * @param errorMessage the value for T_SHIA_SYNCHRO_RISK_INFO.ERROR_MESSAGE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.POLICY_SEQUENCE_NO
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.POLICY_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getPolicySequenceNo() {
        return policySequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.POLICY_SEQUENCE_NO
     *
     * @param policySequenceNo the value for T_SHIA_SYNCHRO_RISK_INFO.POLICY_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setPolicySequenceNo(String policySequenceNo) {
        this.policySequenceNo = policySequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.UNDERWRIT_SEQUENCE_NO
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.UNDERWRIT_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getUnderwritSequenceNo() {
        return underwritSequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.UNDERWRIT_SEQUENCE_NO
     *
     * @param underwritSequenceNo the value for T_SHIA_SYNCHRO_RISK_INFO.UNDERWRIT_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setUnderwritSequenceNo(String underwritSequenceNo) {
        this.underwritSequenceNo = underwritSequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.CUTOMER_SEQUENCE_NO
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.CUTOMER_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getCutomerSequenceNo() {
        return cutomerSequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.CUTOMER_SEQUENCE_NO
     *
     * @param cutomerSequenceNo the value for T_SHIA_SYNCHRO_RISK_INFO.CUTOMER_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setCutomerSequenceNo(String cutomerSequenceNo) {
        this.cutomerSequenceNo = cutomerSequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.START_TIME
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.START_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.START_TIME
     *
     * @param startTime the value for T_SHIA_SYNCHRO_RISK_INFO.START_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.END_TIME
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.END_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.END_TIME
     *
     * @param endTime the value for T_SHIA_SYNCHRO_RISK_INFO.END_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_LIFE_SUM_INSURED
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.ALL_LIFE_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public BigDecimal getAllLifeSumInsured() {
        return allLifeSumInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_LIFE_SUM_INSURED
     *
     * @param allLifeSumInsured the value for T_SHIA_SYNCHRO_RISK_INFO.ALL_LIFE_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setAllLifeSumInsured(BigDecimal allLifeSumInsured) {
        this.allLifeSumInsured = allLifeSumInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_ACCIDENT_SUM_INSURED
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.ALL_ACCIDENT_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public BigDecimal getAllAccidentSumInsured() {
        return allAccidentSumInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_ACCIDENT_SUM_INSURED
     *
     * @param allAccidentSumInsured the value for T_SHIA_SYNCHRO_RISK_INFO.ALL_ACCIDENT_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setAllAccidentSumInsured(BigDecimal allAccidentSumInsured) {
        this.allAccidentSumInsured = allAccidentSumInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_HEALTH_SUM_INSURED
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.ALL_HEALTH_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public BigDecimal getAllHealthSumInsured() {
        return allHealthSumInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_HEALTH_SUM_INSURED
     *
     * @param allHealthSumInsured the value for T_SHIA_SYNCHRO_RISK_INFO.ALL_HEALTH_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setAllHealthSumInsured(BigDecimal allHealthSumInsured) {
        this.allHealthSumInsured = allHealthSumInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_OLD_SUM_INSURED
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.ALL_OLD_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public BigDecimal getAllOldSumInsured() {
        return allOldSumInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_OLD_SUM_INSURED
     *
     * @param allOldSumInsured the value for T_SHIA_SYNCHRO_RISK_INFO.ALL_OLD_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setAllOldSumInsured(BigDecimal allOldSumInsured) {
        this.allOldSumInsured = allOldSumInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_OTHER_SUM_INSURED
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.ALL_OTHER_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public BigDecimal getAllOtherSumInsured() {
        return allOtherSumInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_OTHER_SUM_INSURED
     *
     * @param allOtherSumInsured the value for T_SHIA_SYNCHRO_RISK_INFO.ALL_OTHER_SUM_INSURED
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setAllOtherSumInsured(BigDecimal allOtherSumInsured) {
        this.allOtherSumInsured = allOtherSumInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_HOSPITAL_ALLOWANCE
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.ALL_HOSPITAL_ALLOWANCE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public BigDecimal getAllHospitalAllowance() {
        return allHospitalAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_HOSPITAL_ALLOWANCE
     *
     * @param allHospitalAllowance the value for T_SHIA_SYNCHRO_RISK_INFO.ALL_HOSPITAL_ALLOWANCE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setAllHospitalAllowance(BigDecimal allHospitalAllowance) {
        this.allHospitalAllowance = allHospitalAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_CLAIM_AMOUNT
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.ALL_CLAIM_AMOUNT
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public BigDecimal getAllClaimAmount() {
        return allClaimAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.ALL_CLAIM_AMOUNT
     *
     * @param allClaimAmount the value for T_SHIA_SYNCHRO_RISK_INFO.ALL_CLAIM_AMOUNT
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setAllClaimAmount(BigDecimal allClaimAmount) {
        this.allClaimAmount = allClaimAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.INSERT_TIME
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.INSERT_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.INSERT_TIME
     *
     * @param insertTime the value for T_SHIA_SYNCHRO_RISK_INFO.INSERT_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.LAST_MODIFY_TIME
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.LAST_MODIFY_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for T_SHIA_SYNCHRO_RISK_INFO.LAST_MODIFY_TIME
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.OPERATOR
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.OPERATOR
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.OPERATOR
     *
     * @param operator the value for T_SHIA_SYNCHRO_RISK_INFO.OPERATOR
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.CLAIM_SEQUENCE_NO
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.CLAIM_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getClaimSequenceNo() {
        return claimSequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.CLAIM_SEQUENCE_NO
     *
     * @param claimSequenceNo the value for T_SHIA_SYNCHRO_RISK_INFO.CLAIM_SEQUENCE_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setClaimSequenceNo(String claimSequenceNo) {
        this.claimSequenceNo = claimSequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.CUSTOMER_NO
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.CUSTOMER_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.CUSTOMER_NO
     *
     * @param customerNo the value for T_SHIA_SYNCHRO_RISK_INFO.CUSTOMER_NO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHIA_SYNCHRO_RISK_INFO.RISK_TYPE
     *
     * @return the value of T_SHIA_SYNCHRO_RISK_INFO.RISK_TYPE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public String getRiskType() {
        return riskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHIA_SYNCHRO_RISK_INFO.RISK_TYPE
     *
     * @param riskType the value for T_SHIA_SYNCHRO_RISK_INFO.RISK_TYPE
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    public void setRiskType(String riskType) {
        this.riskType = riskType;
    }
}