package com.sinosoft.ummp.domain.model;

public class TTempNode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEMP_NODE.ID
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEMP_NODE.FID
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEMP_NODE.NODE_ID
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    private String nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEMP_NODE.NODE_CODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    private String nodeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEMP_NODE.NODE_NAME
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEMP_NODE.SON_NODE_TYPE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    private String sonNodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEMP_NODE.SON_NODE_CONTENET
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    private String sonNodeContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEMP_NODE.ID
     *
     * @return the value of T_TEMP_NODE.ID
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEMP_NODE.ID
     *
     * @param id the value for T_TEMP_NODE.ID
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEMP_NODE.FID
     *
     * @return the value of T_TEMP_NODE.FID
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEMP_NODE.FID
     *
     * @param fid the value for T_TEMP_NODE.FID
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEMP_NODE.NODE_ID
     *
     * @return the value of T_TEMP_NODE.NODE_ID
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEMP_NODE.NODE_ID
     *
     * @param nodeId the value for T_TEMP_NODE.NODE_ID
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEMP_NODE.NODE_CODE
     *
     * @return the value of T_TEMP_NODE.NODE_CODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public String getNodeCode() {
        return nodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEMP_NODE.NODE_CODE
     *
     * @param nodeCode the value for T_TEMP_NODE.NODE_CODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public void setNodeCode(String nodeCode) {
        this.nodeCode = nodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEMP_NODE.NODE_NAME
     *
     * @return the value of T_TEMP_NODE.NODE_NAME
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEMP_NODE.NODE_NAME
     *
     * @param nodeName the value for T_TEMP_NODE.NODE_NAME
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEMP_NODE.SON_NODE_TYPE
     *
     * @return the value of T_TEMP_NODE.SON_NODE_TYPE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public String getSonNodeType() {
        return sonNodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEMP_NODE.SON_NODE_TYPE
     *
     * @param sonNodeType the value for T_TEMP_NODE.SON_NODE_TYPE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public void setSonNodeType(String sonNodeType) {
        this.sonNodeType = sonNodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEMP_NODE.SON_NODE_CONTENET
     *
     * @return the value of T_TEMP_NODE.SON_NODE_CONTENET
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public String getSonNodeContent() {
        return sonNodeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEMP_NODE.SON_NODE_CONTENET
     *
     * @param sonNodeContent the value for T_TEMP_NODE.SON_NODE_CONTENET
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    public void setSonNodeContent(String sonNodeContent) {
        this.sonNodeContent = sonNodeContent;
    }

	@Override
	public String toString() {
		return "TTempNode [id=" + id + ", fid=" + fid + ", nodeId=" + nodeId
				+ ", nodeCode=" + nodeCode + ", nodeName=" + nodeName
				+ ", sonNodeType=" + sonNodeType + ", sonNodeContent="
				+ sonNodeContent + "]";
	}
    
}