package com.sinosoft.ummp.domain.model;

import java.util.ArrayList;
import java.util.List;

public class TTempNodeAttriExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public TTempNodeAttriExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNodeIdIsNull() {
            addCriterion("NODE_ID is null");
            return (Criteria) this;
        }

        public Criteria andNodeIdIsNotNull() {
            addCriterion("NODE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andNodeIdEqualTo(Integer value) {
            addCriterion("NODE_ID =", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdNotEqualTo(Integer value) {
            addCriterion("NODE_ID <>", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdGreaterThan(Integer value) {
            addCriterion("NODE_ID >", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("NODE_ID >=", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdLessThan(Integer value) {
            addCriterion("NODE_ID <", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdLessThanOrEqualTo(Integer value) {
            addCriterion("NODE_ID <=", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdIn(List<Integer> values) {
            addCriterion("NODE_ID in", values, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdNotIn(List<Integer> values) {
            addCriterion("NODE_ID not in", values, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdBetween(Integer value1, Integer value2) {
            addCriterion("NODE_ID between", value1, value2, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("NODE_ID not between", value1, value2, "nodeId");
            return (Criteria) this;
        }

        public Criteria andAttriCodeIsNull() {
            addCriterion("ATTRI_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAttriCodeIsNotNull() {
            addCriterion("ATTRI_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAttriCodeEqualTo(String value) {
            addCriterion("ATTRI_CODE =", value, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeNotEqualTo(String value) {
            addCriterion("ATTRI_CODE <>", value, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeGreaterThan(String value) {
            addCriterion("ATTRI_CODE >", value, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ATTRI_CODE >=", value, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeLessThan(String value) {
            addCriterion("ATTRI_CODE <", value, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeLessThanOrEqualTo(String value) {
            addCriterion("ATTRI_CODE <=", value, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeLike(String value) {
            addCriterion("ATTRI_CODE like", value, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeNotLike(String value) {
            addCriterion("ATTRI_CODE not like", value, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeIn(List<String> values) {
            addCriterion("ATTRI_CODE in", values, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeNotIn(List<String> values) {
            addCriterion("ATTRI_CODE not in", values, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeBetween(String value1, String value2) {
            addCriterion("ATTRI_CODE between", value1, value2, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriCodeNotBetween(String value1, String value2) {
            addCriterion("ATTRI_CODE not between", value1, value2, "attriCode");
            return (Criteria) this;
        }

        public Criteria andAttriNameIsNull() {
            addCriterion("ATTRI_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAttriNameIsNotNull() {
            addCriterion("ATTRI_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAttriNameEqualTo(String value) {
            addCriterion("ATTRI_NAME =", value, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameNotEqualTo(String value) {
            addCriterion("ATTRI_NAME <>", value, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameGreaterThan(String value) {
            addCriterion("ATTRI_NAME >", value, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameGreaterThanOrEqualTo(String value) {
            addCriterion("ATTRI_NAME >=", value, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameLessThan(String value) {
            addCriterion("ATTRI_NAME <", value, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameLessThanOrEqualTo(String value) {
            addCriterion("ATTRI_NAME <=", value, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameLike(String value) {
            addCriterion("ATTRI_NAME like", value, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameNotLike(String value) {
            addCriterion("ATTRI_NAME not like", value, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameIn(List<String> values) {
            addCriterion("ATTRI_NAME in", values, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameNotIn(List<String> values) {
            addCriterion("ATTRI_NAME not in", values, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameBetween(String value1, String value2) {
            addCriterion("ATTRI_NAME between", value1, value2, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriNameNotBetween(String value1, String value2) {
            addCriterion("ATTRI_NAME not between", value1, value2, "attriName");
            return (Criteria) this;
        }

        public Criteria andAttriTypeIsNull() {
            addCriterion("ATTRI_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAttriTypeIsNotNull() {
            addCriterion("ATTRI_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAttriTypeEqualTo(String value) {
            addCriterion("ATTRI_TYPE =", value, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeNotEqualTo(String value) {
            addCriterion("ATTRI_TYPE <>", value, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeGreaterThan(String value) {
            addCriterion("ATTRI_TYPE >", value, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ATTRI_TYPE >=", value, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeLessThan(String value) {
            addCriterion("ATTRI_TYPE <", value, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeLessThanOrEqualTo(String value) {
            addCriterion("ATTRI_TYPE <=", value, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeLike(String value) {
            addCriterion("ATTRI_TYPE like", value, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeNotLike(String value) {
            addCriterion("ATTRI_TYPE not like", value, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeIn(List<String> values) {
            addCriterion("ATTRI_TYPE in", values, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeNotIn(List<String> values) {
            addCriterion("ATTRI_TYPE not in", values, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeBetween(String value1, String value2) {
            addCriterion("ATTRI_TYPE between", value1, value2, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriTypeNotBetween(String value1, String value2) {
            addCriterion("ATTRI_TYPE not between", value1, value2, "attriType");
            return (Criteria) this;
        }

        public Criteria andAttriValueIsNull() {
            addCriterion("ATTRI_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andAttriValueIsNotNull() {
            addCriterion("ATTRI_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andAttriValueEqualTo(String value) {
            addCriterion("ATTRI_VALUE =", value, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueNotEqualTo(String value) {
            addCriterion("ATTRI_VALUE <>", value, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueGreaterThan(String value) {
            addCriterion("ATTRI_VALUE >", value, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueGreaterThanOrEqualTo(String value) {
            addCriterion("ATTRI_VALUE >=", value, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueLessThan(String value) {
            addCriterion("ATTRI_VALUE <", value, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueLessThanOrEqualTo(String value) {
            addCriterion("ATTRI_VALUE <=", value, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueLike(String value) {
            addCriterion("ATTRI_VALUE like", value, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueNotLike(String value) {
            addCriterion("ATTRI_VALUE not like", value, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueIn(List<String> values) {
            addCriterion("ATTRI_VALUE in", values, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueNotIn(List<String> values) {
            addCriterion("ATTRI_VALUE not in", values, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueBetween(String value1, String value2) {
            addCriterion("ATTRI_VALUE between", value1, value2, "attriValue");
            return (Criteria) this;
        }

        public Criteria andAttriValueNotBetween(String value1, String value2) {
            addCriterion("ATTRI_VALUE not between", value1, value2, "attriValue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 21 10:57:47 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_TEMP_NODE_ATTRI
     *
     * @mbggenerated Tue Jun 21 10:57:47 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}