package com.sinosoft.platform.quartz.domain.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.quartz.domain.model.QrtzCalendars;
import com.sinosoft.platform.quartz.domain.model.QrtzCalendarsExample;

public interface QrtzCalendarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    int countByExample(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    int deleteByExample(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    int deleteByPrimaryKey(String calendarName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    int insert(QrtzCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    int insertSelective(QrtzCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    List<QrtzCalendars> selectByExampleWithBLOBs(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    List<QrtzCalendars> selectByExample(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    QrtzCalendars selectByPrimaryKey(String calendarName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") QrtzCalendars record, @Param("example") QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") QrtzCalendars record, @Param("example") QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    int updateByExample(@Param("record") QrtzCalendars record, @Param("example") QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    int updateByPrimaryKeySelective(QrtzCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(QrtzCalendars record);
}