package com.sinosoft.platform.quartz.domain.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.quartz.domain.model.QrtzTriggerLog;
import com.sinosoft.platform.quartz.domain.model.QrtzTriggerLogExample;

public interface QrtzTriggerLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	int countByExample(QrtzTriggerLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	int deleteByExample(QrtzTriggerLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	int insert(QrtzTriggerLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	int insertSelective(QrtzTriggerLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	List<QrtzTriggerLog> selectByExample(QrtzTriggerLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	QrtzTriggerLog selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	int updateByExampleSelective(@Param("record") QrtzTriggerLog record,
			@Param("example") QrtzTriggerLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	int updateByExample(@Param("record") QrtzTriggerLog record,
			@Param("example") QrtzTriggerLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	int updateByPrimaryKeySelective(QrtzTriggerLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_TRIGER_LOG
	 * @mbggenerated  Mon Aug 15 11:58:13 CST 2016
	 */
	int updateByPrimaryKey(QrtzTriggerLog record);
}