package com.sinosoft.platform.core.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.core.domain.model.DefRole;
import com.sinosoft.platform.core.domain.model.DefRoleExample;

public interface DefRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int countByExample(DefRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int deleteByExample(DefRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int insert(DefRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int insertSelective(DefRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    List<DefRole> selectByExample(DefRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    DefRole selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") DefRole record, @Param("example") DefRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int updateByExample(@Param("record") DefRole record, @Param("example") DefRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int updateByPrimaryKeySelective(DefRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int updateByPrimaryKey(DefRole record);
}