package com.sinosoft.platform.core.domain.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.core.domain.model.DefUserRoleRela;
import com.sinosoft.platform.core.domain.model.DefUserRoleRelaExample;

public interface DefUserRoleRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int countByExample(DefUserRoleRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int deleteByExample(DefUserRoleRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int insert(DefUserRoleRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int insertSelective(DefUserRoleRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    List<DefUserRoleRela> selectByExample(DefUserRoleRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    DefUserRoleRela selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") DefUserRoleRela record, @Param("example") DefUserRoleRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int updateByExample(@Param("record") DefUserRoleRela record, @Param("example") DefUserRoleRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int updateByPrimaryKeySelective(DefUserRoleRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_USER_ROLE_RELA
     *
     * @mbggenerated Thu May 12 09:48:03 CST 2016
     */
    int updateByPrimaryKey(DefUserRoleRela record);
    /**
     * 通过ID和Code删除角色
     * @param map
     * @return
     */
    @SuppressWarnings("rawtypes")
	int deleteU2RByUserIdAndCode(Map map);
}