package com.sinosoft.platform.core.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.core.domain.model.TDefRole;
import com.sinosoft.platform.core.domain.model.TDefRoleExample;

public interface TDefRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    int countByExample(TDefRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    int deleteByExample(TDefRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    int insert(TDefRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    int insertSelective(TDefRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    List<TDefRole> selectByExample(TDefRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    TDefRole selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefRole record, @Param("example") TDefRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    int updateByExample(@Param("record") TDefRole record, @Param("example") TDefRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    int updateByPrimaryKeySelective(TDefRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_ROLE
     *
     * @mbggenerated Thu Jun 30 18:49:17 CST 2016
     */
    int updateByPrimaryKey(TDefRole record);
    /**
     * 根据用户编码获取对应的ROLE
     * @param userCode
     * @return
     */
    List<TDefRole> selectByUserCode(String userCode);
}