package com.sinosoft.platform.core.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.core.domain.model.TDefJdbc;
import com.sinosoft.platform.core.domain.model.TDefJdbcExample;

public interface TDefJdbcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int countByExample(TDefJdbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int deleteByExample(TDefJdbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int insert(TDefJdbc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int insertSelective(TDefJdbc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    List<TDefJdbc> selectByExample(TDefJdbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    TDefJdbc selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefJdbc record, @Param("example") TDefJdbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByExample(@Param("record") TDefJdbc record, @Param("example") TDefJdbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByPrimaryKeySelective(TDefJdbc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_JDBC
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByPrimaryKey(TDefJdbc record);
}