package com.sinosoft.platform.core.domain.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.core.domain.model.TDefCodeDict;
import com.sinosoft.platform.core.domain.model.TDefCodeDictExample;

public interface TDefCodeDictMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_DICT
	 * @mbggenerated  Sun Nov 20 17:48:38 CST 2016
	 */
	int countByExample(TDefCodeDictExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_DICT
	 * @mbggenerated  Sun Nov 20 17:48:38 CST 2016
	 */
	int deleteByExample(TDefCodeDictExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_DICT
	 * @mbggenerated  Sun Nov 20 17:48:38 CST 2016
	 */
	int insert(TDefCodeDict record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_DICT
	 * @mbggenerated  Sun Nov 20 17:48:38 CST 2016
	 */
	int insertSelective(TDefCodeDict record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_DICT
	 * @mbggenerated  Sun Nov 20 17:48:38 CST 2016
	 */
	List<TDefCodeDict> selectByExample(TDefCodeDictExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_DICT
	 * @mbggenerated  Sun Nov 20 17:48:38 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TDefCodeDict record,
			@Param("example") TDefCodeDictExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_DICT
	 * @mbggenerated  Sun Nov 20 17:48:38 CST 2016
	 */
	int updateByExample(@Param("record") TDefCodeDict record,
			@Param("example") TDefCodeDictExample example);
	/**
     * CodeDict 分页查询
     * @param paramMap
     * @return
     */
    @SuppressWarnings("rawtypes")
	public List<Map> queryCodedictListInfoPages(Map paramMap);
    /**
     * 分页统计
     * @param paramMap
     * @return
     */
	@SuppressWarnings("rawtypes")
	public Integer queryCodedictListInfoCounts(Map paramMap);
	/**
	 * 查询类型类型
	 * @return
	 */
	public List<String> codeQueryType();
	
	/**
	 * 查询目标�?
	 */
	List<String> selectExportTab();
	
	/**
	 * 获得目标表名
	 * @return String
	 */
	TDefCodeDict selectExportTabName(String exportDataTab);
	
	/**
	 * 构造最近10年下拉框
	 * @return
	 */
	public List<String> selectExportDataYear();
}