package com.sinosoft.platform.core.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.core.domain.model.TDefSqlParams;
import com.sinosoft.platform.core.domain.model.TDefSqlParamsExample;

public interface TDefSqlParamsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	int countByExample(TDefSqlParamsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	int deleteByExample(TDefSqlParamsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	int insert(TDefSqlParams record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	int insertSelective(TDefSqlParams record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	List<TDefSqlParams> selectByExample(TDefSqlParamsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	TDefSqlParams selectByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TDefSqlParams record,
			@Param("example") TDefSqlParamsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	int updateByExample(@Param("record") TDefSqlParams record,
			@Param("example") TDefSqlParamsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	int updateByPrimaryKeySelective(TDefSqlParams record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL_PARAMS
	 * @mbggenerated  Fri Jul 08 11:30:12 CST 2016
	 */
	int updateByPrimaryKey(TDefSqlParams record);
	/**
	 * 根据SQLID获取SQL参数
	 * @param id
	 * @return
	 */
	List<TDefSqlParams> selectBySqlId(BigDecimal id);
}