package com.sinosoft.platform.core.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.core.domain.model.TDefPlatRoleRela;
import com.sinosoft.platform.core.domain.model.TDefPlatRoleRelaExample;

public interface TDefPlatRoleRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    int countByExample(TDefPlatRoleRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    int deleteByExample(TDefPlatRoleRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    int insert(TDefPlatRoleRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    int insertSelective(TDefPlatRoleRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    List<TDefPlatRoleRela> selectByExample(TDefPlatRoleRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    TDefPlatRoleRela selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefPlatRoleRela record, @Param("example") TDefPlatRoleRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    int updateByExample(@Param("record") TDefPlatRoleRela record, @Param("example") TDefPlatRoleRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    int updateByPrimaryKeySelective(TDefPlatRoleRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_PLAT_ROLE_RELA
     *
     * @mbggenerated Wed May 25 13:19:59 CST 2016
     */
    int updateByPrimaryKey(TDefPlatRoleRela record);
}