package com.sinosoft.platform.core.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.core.domain.model.TDefSqlInfo;
import com.sinosoft.platform.core.domain.model.TDefSqlInfoExample;

public interface TDefSqlInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int countByExample(TDefSqlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int deleteByExample(TDefSqlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int insert(TDefSqlInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int insertSelective(TDefSqlInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    List<TDefSqlInfo> selectByExampleWithBLOBs(TDefSqlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    List<TDefSqlInfo> selectByExample(TDefSqlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    TDefSqlInfo selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefSqlInfo record, @Param("example") TDefSqlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") TDefSqlInfo record, @Param("example") TDefSqlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByExample(@Param("record") TDefSqlInfo record, @Param("example") TDefSqlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByPrimaryKeySelective(TDefSqlInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TDefSqlInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SQL_INFO
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByPrimaryKey(TDefSqlInfo record);
    /**
     * 根据SqlId获取SQL基本信息(不包含Blob)
     * @param sqlId
     * @return
     */
    List<TDefSqlInfo> selectBySqlId(BigDecimal sqlId);
    /**
     * 根据SqlId获取SQL信息获取(包含Blob)
     * @param sqlId
     * @return
     */
    List<TDefSqlInfo> selectBySqlIdWithBLOBs(BigDecimal sqlId);
}