package com.sinosoft.platform.core.domain.mapper;

import com.sinosoft.platform.core.domain.model.TDefJobLog;
import com.sinosoft.platform.core.domain.model.TDefJobLogExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDefJobLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:19 CST 2016
	 */
	int countByExample(TDefJobLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:19 CST 2016
	 */
	int deleteByExample(TDefJobLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:19 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:19 CST 2016
	 */
	int insert(TDefJobLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:19 CST 2016
	 */
	int insertSelective(TDefJobLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:19 CST 2016
	 */
	List<TDefJobLog> selectByExample(TDefJobLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:19 CST 2016
	 */
	TDefJobLog selectByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TDefJobLog record,
			@Param("example") TDefJobLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:20 CST 2016
	 */
	int updateByExample(@Param("record") TDefJobLog record,
			@Param("example") TDefJobLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:20 CST 2016
	 */
	int updateByPrimaryKeySelective(TDefJobLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_JOB_LOG
	 * @mbggenerated  Thu Sep 01 17:41:20 CST 2016
	 */
	int updateByPrimaryKey(TDefJobLog record);
}