package com.sinosoft.platform.core.domain.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.core.domain.model.TDefSql;
import com.sinosoft.platform.core.domain.model.TDefSqlExample;

public interface TDefSqlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	int countByExample(TDefSqlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	int deleteByExample(TDefSqlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal sqlId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	int insert(TDefSql record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	int insertSelective(TDefSql record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public List<TDefSql> selectByExample(TDefSqlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	public TDefSql selectByPrimaryKey(BigDecimal sqlId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TDefSql record,
			@Param("example") TDefSqlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	int updateByExample(@Param("record") TDefSql record,
			@Param("example") TDefSqlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	int updateByPrimaryKeySelective(TDefSql record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_SQL
	 * @mbggenerated  Wed Jun 29 20:21:30 CST 2016
	 */
	int updateByPrimaryKey(TDefSql record);

	@SuppressWarnings("rawtypes")
	public Integer querySqlListInfoCounts(Map paramMap);
	@SuppressWarnings("rawtypes")
	public List<Map> querySqlListInfoPages(Map paramMap);
	@SuppressWarnings("rawtypes")
	public List<Map> querySqlListInfo();
	@SuppressWarnings("rawtypes")
	public List<Map> queryMonitorName();

	public BigDecimal getSqlIdBySqlCode(String sqlCode);

	//查询批处理配置脚本
	public List<Map<String, Object>> selectBatchConfigSQL(Map<String,Object> paramMap);

	public int selectCountBatchConfigSQL();

	/**
	 * 根据SQLID获取SQL
	 * @param sqlId
	 * @return
	 */
	public String getSqlById(BigDecimal sqlId);

}