package com.sinosoft.platform.core.domain.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.platform.core.domain.model.TDefCodeMapping;
import com.sinosoft.platform.core.domain.model.TDefCodeMappingExample;

public interface TDefCodeMappingMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	int countByExample(TDefCodeMappingExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	int deleteByExample(TDefCodeMappingExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	int insert(TDefCodeMapping record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	int insertSelective(TDefCodeMapping record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	List<TDefCodeMapping> selectByExample(TDefCodeMappingExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	TDefCodeMapping selectByPrimaryKey(BigDecimal id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TDefCodeMapping record,
			@Param("example") TDefCodeMappingExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	int updateByExample(@Param("record") TDefCodeMapping record,
			@Param("example") TDefCodeMappingExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	int updateByPrimaryKeySelective(TDefCodeMapping record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_CODE_MAPPING
	 * @mbggenerated  Wed Aug 31 15:26:12 CST 2016
	 */
	int updateByPrimaryKey(TDefCodeMapping record);
	/**
	 * Count by Record Add By Darker.Wang
	 * @param record
	 * @return
	 */
	int countByRecord(TDefCodeMapping record);
	/**
	 * @param model
	 * @return
	 */
	@SuppressWarnings("rawtypes")
	List<Map> selectByPage(Map param);

	/**
	 * @return
	 */
	@SuppressWarnings("rawtypes")
	List<Map> selectCodeType();
}