package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefNotice;
import com.sinosoft.ummp.domain.model.TDefNoticeExample;

public interface TDefNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int countByExample(TDefNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByExample(TDefNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insert(TDefNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insertSelective(TDefNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    List<TDefNotice> selectByExample(TDefNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    TDefNotice selectByPrimaryKey(BigDecimal noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefNotice record, @Param("example") TDefNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExample(@Param("record") TDefNotice record, @Param("example") TDefNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKeySelective(TDefNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKey(TDefNotice record);
}