package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefNoticeMain;
import com.sinosoft.ummp.domain.model.TDefNoticeMainExample;

public interface TDefNoticeMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int countByExample(TDefNoticeMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByExample(TDefNoticeMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insert(TDefNoticeMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insertSelective(TDefNoticeMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    List<TDefNoticeMain> selectByExample(TDefNoticeMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    TDefNoticeMain selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefNoticeMain record, @Param("example") TDefNoticeMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExample(@Param("record") TDefNoticeMain record, @Param("example") TDefNoticeMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKeySelective(TDefNoticeMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_MAIN
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKey(TDefNoticeMain record);

public Integer queryMainListInfoCounts(Map paramMap);
	
	
	/**
	 * 抄送邮箱信息列表查询（分页查询）
	 * @param paramMap
	 * @return
	 */
	public List<Map> queryMainListInfoPages(Map paramMap);
}