package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefBussImpl;
import com.sinosoft.ummp.domain.model.TDefBussImplExample;

public interface TDefBussImplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    int countByExample(TDefBussImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    int deleteByExample(TDefBussImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal implId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    int insert(TDefBussImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    int insertSelective(TDefBussImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    List<TDefBussImpl> selectByExample(TDefBussImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    TDefBussImpl selectByPrimaryKey(BigDecimal implId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefBussImpl record, @Param("example") TDefBussImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    int updateByExample(@Param("record") TDefBussImpl record, @Param("example") TDefBussImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    int updateByPrimaryKeySelective(TDefBussImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_IMPL
     *
     * @mbggenerated Fri Jul 01 16:37:31 CST 2016
     */
    int updateByPrimaryKey(TDefBussImpl record);
}