package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefActionTrace;
import com.sinosoft.ummp.domain.model.TDefActionTraceExample;

public interface TDefActionTraceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	int countByExample(TDefActionTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	int deleteByExample(TDefActionTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	int insert(TDefActionTrace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	int insertSelective(TDefActionTrace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	List<TDefActionTrace> selectByExample(TDefActionTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	TDefActionTrace selectByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TDefActionTrace record,
			@Param("example") TDefActionTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	int updateByExample(@Param("record") TDefActionTrace record,
			@Param("example") TDefActionTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	int updateByPrimaryKeySelective(TDefActionTrace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_ACTION_TRACE
	 * @mbggenerated  Thu Nov 03 19:09:11 CST 2016
	 */
	int updateByPrimaryKey(TDefActionTrace record);

	List<Map> exportExcel(Map paramMap);

	int queryCount(Map paramMap);

	List<Map> exportExcell(Map paramMap);

	List<Map> exportExtractExcel(Map paramMap);

	int listCount(Map paramMap);

	List<Map> listExcel(Map paramMap);
	
	int querySubmitReturnInfoCounts(Map paramMap);
	
	List<Map> querySubmitReturnInfoPages(Map paramMap);
}