package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefMonitor;
import com.sinosoft.ummp.domain.model.TDefMonitorExample;

public interface TDefMonitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int countByExample(TDefMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByExample(TDefMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal monitorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insert(TDefMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insertSelective(TDefMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    List<TDefMonitor> selectByExample(TDefMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    TDefMonitor selectByPrimaryKey(BigDecimal monitorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefMonitor record, @Param("example") TDefMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExample(@Param("record") TDefMonitor record, @Param("example") TDefMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKeySelective(TDefMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKey(TDefMonitor record);
    /**
     * 获取有效的监控时间包
     * @return
     */
    List<TDefMonitor> selectUsableMonitors();
}