package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefSend;
import com.sinosoft.ummp.domain.model.TDefSendExample;

public interface TDefSendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    int countByExample(TDefSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    int deleteByExample(TDefSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    int insert(TDefSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    int insertSelective(TDefSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    List<TDefSend> selectByExample(TDefSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    TDefSend selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefSend record, @Param("example") TDefSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    int updateByExample(@Param("record") TDefSend record, @Param("example") TDefSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    int updateByPrimaryKeySelective(TDefSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_SEND
     *
     * @mbggenerated Thu Jun 30 13:27:23 CST 2016
     */
    int updateByPrimaryKey(TDefSend record);
    /**
     * 根据平台结构获取对应的报送模型
     * @param comId
     * @return
     */
    List<TDefSend> selectByComId(BigDecimal comId);
}