package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefWSPReturn;
import com.sinosoft.ummp.domain.model.TDefWSPReturnExample;

public interface TDefWSPReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    int countByExample(TDefWSPReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    int deleteByExample(TDefWSPReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    int insert(TDefWSPReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    int insertSelective(TDefWSPReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    List<TDefWSPReturn> selectByExample(TDefWSPReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    TDefWSPReturn selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefWSPReturn record, @Param("example") TDefWSPReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    int updateByExample(@Param("record") TDefWSPReturn record, @Param("example") TDefWSPReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    int updateByPrimaryKeySelective(TDefWSPReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_WSP_RETURN
     *
     * @mbggenerated Thu Jul 28 14:10:50 CST 2016
     */
    int updateByPrimaryKey(TDefWSPReturn record);
    
    /**
     * 根据请求ID获取到对应的参数信息（有序性）
     * @param requestId
     * @return
     */
    List<TDefWSPReturn> selectByRequestId(BigDecimal requestId);
}