package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefMsgNodeAttri;
import com.sinosoft.ummp.domain.model.TDefMsgNodeAttriExample;

public interface TDefMsgNodeAttriMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int countByExample(TDefMsgNodeAttriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int deleteByExample(TDefMsgNodeAttriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int insert(TDefMsgNodeAttri record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int insertSelective(TDefMsgNodeAttri record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    List<TDefMsgNodeAttri> selectByExample(TDefMsgNodeAttriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    TDefMsgNodeAttri selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefMsgNodeAttri record, @Param("example") TDefMsgNodeAttriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByExample(@Param("record") TDefMsgNodeAttri record, @Param("example") TDefMsgNodeAttriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByPrimaryKeySelective(TDefMsgNodeAttri record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MSG_NODE_ATTRI
     *
     * @mbggenerated Wed Jun 15 16:31:06 CST 2016
     */
    int updateByPrimaryKey(TDefMsgNodeAttri record);
    /**
     * 通过NodeId获取其属性 
     * @param nodeId
     * @return
     */
    List<TDefMsgNodeAttri> selectByNodeId(BigDecimal nodeId);
    /**
     * 根据根节点递归删除所有节点对应参数，系统参数除外
     * @param nodeId
     * @return
     */
    int deleteByNodeIdRecycle(BigDecimal nodeId);
}