package com.sinosoft.ummp.domain.mapper;

import com.sinosoft.ummp.domain.model.TDefTranscodeTrace;
import com.sinosoft.ummp.domain.model.TDefTranscodeTraceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDefTranscodeTraceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSCODE_TRACE
	 * @mbggenerated  Sun Oct 09 13:28:37 CST 2016
	 */
	int countByExample(TDefTranscodeTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSCODE_TRACE
	 * @mbggenerated  Sun Oct 09 13:28:37 CST 2016
	 */
	int deleteByExample(TDefTranscodeTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSCODE_TRACE
	 * @mbggenerated  Sun Oct 09 13:28:37 CST 2016
	 */
	int insert(TDefTranscodeTrace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSCODE_TRACE
	 * @mbggenerated  Sun Oct 09 13:28:37 CST 2016
	 */
	int insertSelective(TDefTranscodeTrace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSCODE_TRACE
	 * @mbggenerated  Sun Oct 09 13:28:37 CST 2016
	 */
	List<TDefTranscodeTrace> selectByExample(TDefTranscodeTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSCODE_TRACE
	 * @mbggenerated  Sun Oct 09 13:28:37 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TDefTranscodeTrace record,
			@Param("example") TDefTranscodeTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_TRANSCODE_TRACE
	 * @mbggenerated  Sun Oct 09 13:28:37 CST 2016
	 */
	int updateByExample(@Param("record") TDefTranscodeTrace record,
			@Param("example") TDefTranscodeTraceExample example);
}