package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefMonitorNoticRela;
import com.sinosoft.ummp.domain.model.TDefMonitorNoticRelaExample;

public interface TDefMonitorNoticRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int countByExample(TDefMonitorNoticRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByExample(TDefMonitorNoticRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insert(TDefMonitorNoticRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insertSelective(TDefMonitorNoticRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    List<TDefMonitorNoticRela> selectByExample(TDefMonitorNoticRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    TDefMonitorNoticRela selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefMonitorNoticRela record, @Param("example") TDefMonitorNoticRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExample(@Param("record") TDefMonitorNoticRela record, @Param("example") TDefMonitorNoticRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKeySelective(TDefMonitorNoticRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_NOTIC_RELA
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKey(TDefMonitorNoticRela record);
}