package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefBagEvent;
import com.sinosoft.ummp.domain.model.TDefBagEventExample;

public interface TDefBagEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    int countByExample(TDefBagEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    int deleteByExample(TDefBagEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    int insert(TDefBagEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    int insertSelective(TDefBagEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    List<TDefBagEvent> selectByExample(TDefBagEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    TDefBagEvent selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefBagEvent record, @Param("example") TDefBagEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    int updateByExample(@Param("record") TDefBagEvent record, @Param("example") TDefBagEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    int updateByPrimaryKeySelective(TDefBagEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BAG_EVENT
     *
     * @mbggenerated Thu Jun 30 19:48:06 CST 2016
     */
    int updateByPrimaryKey(TDefBagEvent record);

	int queryAllCounts(Map paramMap);

	List<Map<String, String>> selectBagEventInfo(Map paramMap);
}