package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefMonitorAction;
import com.sinosoft.ummp.domain.model.TDefMonitorActionExample;

public interface TDefMonitorActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int countByExample(TDefMonitorActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByExample(TDefMonitorActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insert(TDefMonitorAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insertSelective(TDefMonitorAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    List<TDefMonitorAction> selectByExample(TDefMonitorActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    TDefMonitorAction selectByPrimaryKey(BigDecimal actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefMonitorAction record, @Param("example") TDefMonitorActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExample(@Param("record") TDefMonitorAction record, @Param("example") TDefMonitorActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKeySelective(TDefMonitorAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_MONITOR_ACTION
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKey(TDefMonitorAction record);
}