package com.sinosoft.ummp.domain.mapper;

import com.sinosoft.ummp.domain.model.TDefBussModel;
import com.sinosoft.ummp.domain.model.TDefBussModelExample;
import com.sinosoft.ummp.domain.pojo.MsgQueryPOJO;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDefBussModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    int countByExample(TDefBussModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    int deleteByExample(TDefBussModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal bussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    int insert(TDefBussModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    int insertSelective(TDefBussModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    List<TDefBussModel> selectByExample(TDefBussModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    TDefBussModel selectByPrimaryKey(BigDecimal bussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefBussModel record, @Param("example") TDefBussModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    int updateByExample(@Param("record") TDefBussModel record, @Param("example") TDefBussModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    int updateByPrimaryKeySelective(TDefBussModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_MODEL
     *
     * @mbggenerated Tue Aug 09 18:07:17 CST 2016
     */
    int updateByPrimaryKey(TDefBussModel record);
    /**
     * 通过页面POJO查询
     * @param pojo
     * @return
     */
    List selectByPOJO(MsgQueryPOJO pojo);
    /**
     * 通过页面POJO统计记录数
     * @param pojo
     * @return
     */
    int countByPOJO(MsgQueryPOJO pojo);
}