package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefTransCode;
import com.sinosoft.ummp.domain.model.TDefTransCodeExample;

public interface TDefTransCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    int countByExample(TDefTransCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    int deleteByExample(TDefTransCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    int insert(TDefTransCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    int insertSelective(TDefTransCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    List<TDefTransCode> selectByExample(TDefTransCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    TDefTransCode selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefTransCode record, @Param("example") TDefTransCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    int updateByExample(@Param("record") TDefTransCode record, @Param("example") TDefTransCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    int updateByPrimaryKeySelective(TDefTransCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANS_CODE
     *
     * @mbggenerated Mon Jul 18 17:49:35 CST 2016
     */
    int updateByPrimaryKey(TDefTransCode record);

	int selectCount(Map paramMap);

	List<TDefTransCode> selectTransListInfo(Map paramMap);

	List<TDefTransCode> selectTransCodeInfo();
}