package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefNoticeSecretly;
import com.sinosoft.ummp.domain.model.TDefNoticeSecretlyExample;

public interface TDefNoticeSecretlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int countByExample(TDefNoticeSecretlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByExample(TDefNoticeSecretlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insert(TDefNoticeSecretly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int insertSelective(TDefNoticeSecretly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    List<TDefNoticeSecretly> selectByExample(TDefNoticeSecretlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    TDefNoticeSecretly selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefNoticeSecretly record, @Param("example") TDefNoticeSecretlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByExample(@Param("record") TDefNoticeSecretly record, @Param("example") TDefNoticeSecretlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKeySelective(TDefNoticeSecretly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_NOTICE_SECRETLY
     *
     * @mbggenerated Fri Jul 01 17:33:58 CST 2016
     */
    int updateByPrimaryKey(TDefNoticeSecretly record);
}