package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefBussXengin;
import com.sinosoft.ummp.domain.model.TDefBussXenginExample;

public interface TDefBussXenginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    int countByExample(TDefBussXenginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    int deleteByExample(TDefBussXenginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    int insert(TDefBussXengin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    int insertSelective(TDefBussXengin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    List<TDefBussXengin> selectByExample(TDefBussXenginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    TDefBussXengin selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefBussXengin record, @Param("example") TDefBussXenginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    int updateByExample(@Param("record") TDefBussXengin record, @Param("example") TDefBussXenginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    int updateByPrimaryKeySelective(TDefBussXengin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_BUSS_XENGIN
     *
     * @mbggenerated Wed Jun 29 21:11:25 CST 2016
     */
    int updateByPrimaryKey(TDefBussXengin record);
}