package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefTransexcBefore;
import com.sinosoft.ummp.domain.model.TDefTransexcBeforeExample;

public interface TDefTransexcBeforeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    int countByExample(TDefTransexcBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    int deleteByExample(TDefTransexcBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    int insert(TDefTransexcBefore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    int insertSelective(TDefTransexcBefore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    List<TDefTransexcBefore> selectByExample(TDefTransexcBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    TDefTransexcBefore selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDefTransexcBefore record, @Param("example") TDefTransexcBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    int updateByExample(@Param("record") TDefTransexcBefore record, @Param("example") TDefTransexcBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    int updateByPrimaryKeySelective(TDefTransexcBefore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEF_TRANSEXC_BEFORE
     *
     * @mbggenerated Tue Jun 28 10:23:43 CST 2016
     */
    int updateByPrimaryKey(TDefTransexcBefore record);
}