package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDefMsgNode;
import com.sinosoft.ummp.domain.model.TDefMsgNodeExample;

public interface TDefMsgNodeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	int countByExample(TDefMsgNodeExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	int deleteByExample(TDefMsgNodeExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal nodeId);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	int insert(TDefMsgNode record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	int insertSelective(TDefMsgNode record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	List<TDefMsgNode> selectByExample(TDefMsgNodeExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	TDefMsgNode selectByPrimaryKey(BigDecimal nodeId);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TDefMsgNode record,
			@Param("example") TDefMsgNodeExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	int updateByExample(@Param("record") TDefMsgNode record,
			@Param("example") TDefMsgNodeExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	int updateByPrimaryKeySelective(TDefMsgNode record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DEF_MSG_NODE
	 * @mbggenerated  Thu Jul 21 17:09:37 CST 2016
	 */
	int updateByPrimaryKey(TDefMsgNode record);
	/**
	 * 根据ID进行递归查询
	 * @param nodeId
	 * @return
	 */
	List<TDefMsgNode> selectByMsgNodeId(BigDecimal nodeId);
	/**
	 * 根据ID进行递归删除
	 * @param nodeId
	 * @return
	 */
	int deleteByMsgNodeId(BigDecimal nodeId);
	/**
	 * 推送节点到临时表
	 * @param nodeId
	 * @return
	 */
	int push2TempNode(BigDecimal nodeId);
	/**
     * 推送属性到临时表
     * @param nodeId
     * @return
     */
    int push2TempNodeAttri(BigDecimal nodeId);
    /**
     * 推送到
     * @param nodeId
     * @return
     */
    int push2TempNodeParam(BigDecimal nodeId);
}