package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDocMain;
import com.sinosoft.ummp.domain.model.TDocMainExample;

public interface TDocMainMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	int countByExample(TDocMainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	int deleteByExample(TDocMainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal docId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	int insert(TDocMain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	int insertSelective(TDocMain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	List<TDocMain> selectByExample(TDocMainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	TDocMain selectByPrimaryKey(BigDecimal docId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TDocMain record,
			@Param("example") TDocMainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	int updateByExample(@Param("record") TDocMain record,
			@Param("example") TDocMainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	int updateByPrimaryKeySelective(TDocMain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_DOC_MAIN
	 * @mbggenerated  Wed Sep 07 15:38:40 CST 2016
	 */
	int updateByPrimaryKey(TDocMain record);

	int listCount();

	@SuppressWarnings("rawtypes")
	List<Map> listFile(Map map);

	List<Map> queryInfo();
}