package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDocPages;
import com.sinosoft.ummp.domain.model.TDocPagesExample;

public interface TDocPagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int countByExample(TDocPagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int deleteByExample(TDocPagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal pageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int insert(TDocPages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int insertSelective(TDocPages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    List<TDocPages> selectByExample(TDocPagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    TDocPages selectByPrimaryKey(BigDecimal pageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDocPages record, @Param("example") TDocPagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int updateByExample(@Param("record") TDocPages record, @Param("example") TDocPagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int updateByPrimaryKeySelective(TDocPages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_PAGES
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int updateByPrimaryKey(TDocPages record);
}