package com.sinosoft.ummp.domain.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TDocUpdown;
import com.sinosoft.ummp.domain.model.TDocUpdownExample;
import com.sinosoft.ummp.domain.model.TDocUpdownKey;

public interface TDocUpdownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int countByExample(TDocUpdownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int deleteByExample(TDocUpdownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int deleteByPrimaryKey(TDocUpdownKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int insert(TDocUpdown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int insertSelective(TDocUpdown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    List<TDocUpdown> selectByExample(TDocUpdownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    TDocUpdown selectByPrimaryKey(TDocUpdownKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") TDocUpdown record, @Param("example") TDocUpdownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int updateByExample(@Param("record") TDocUpdown record, @Param("example") TDocUpdownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int updateByPrimaryKeySelective(TDocUpdown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DOC_UPDOWN
     *
     * @mbggenerated Wed Jul 27 14:30:04 CST 2016
     */
    int updateByPrimaryKey(TDocUpdown record);

	int countList(Map map);

	List<Map> queryFileList(Map map);
}