package com.sinosoft.ummp.domain.mapper;

import com.sinosoft.ummp.domain.model.TPrpLcpolicydeliveryrate;
import com.sinosoft.ummp.domain.model.TPrpLcpolicydeliveryrateExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TPrpLcpolicydeliveryrateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int countByExample(TPrpLcpolicydeliveryrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int deleteByExample(TPrpLcpolicydeliveryrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int insert(TPrpLcpolicydeliveryrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int insertSelective(TPrpLcpolicydeliveryrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    List<TPrpLcpolicydeliveryrate> selectByExample(TPrpLcpolicydeliveryrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    TPrpLcpolicydeliveryrate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TPrpLcpolicydeliveryrate record, @Param("example") TPrpLcpolicydeliveryrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByExample(@Param("record") TPrpLcpolicydeliveryrate record, @Param("example") TPrpLcpolicydeliveryrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByPrimaryKeySelective(TPrpLcpolicydeliveryrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLICYDELIVERYRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByPrimaryKey(TPrpLcpolicydeliveryrate record);

	List<Map> exportExcel(Map paramMap);
}