package com.sinosoft.ummp.domain.mapper;

import com.sinosoft.ummp.domain.model.TPrpLcpoltransactionReturn;
import com.sinosoft.ummp.domain.model.TPrpLcpoltransactionReturnExample;
import com.sinosoft.ummp.domain.model.TPrpLcpoltransactionReturnKey;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TPrpLcpoltransactionReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    int countByExample(TPrpLcpoltransactionReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    int deleteByExample(TPrpLcpoltransactionReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    int deleteByPrimaryKey(TPrpLcpoltransactionReturnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    int insert(TPrpLcpoltransactionReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    int insertSelective(TPrpLcpoltransactionReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    List<TPrpLcpoltransactionReturn> selectByExample(TPrpLcpoltransactionReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    TPrpLcpoltransactionReturn selectByPrimaryKey(TPrpLcpoltransactionReturnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") TPrpLcpoltransactionReturn record, @Param("example") TPrpLcpoltransactionReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    int updateByExample(@Param("record") TPrpLcpoltransactionReturn record, @Param("example") TPrpLcpoltransactionReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    int updateByPrimaryKeySelective(TPrpLcpoltransactionReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPOLTRANSACTION_RETURN
     *
     * @mbggenerated Tue Oct 11 16:01:08 CST 2016
     */
    int updateByPrimaryKey(TPrpLcpoltransactionReturn record);

	List<Map> selectReturnFile(Map<String,String> map);
}