package com.sinosoft.ummp.domain.mapper;

import com.sinosoft.ummp.domain.model.TPrpLcphonecompleterate;
import com.sinosoft.ummp.domain.model.TPrpLcphonecompleterateExample;
import com.sinosoft.ummp.domain.model.TPrpLcphonecompleterateKey;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TPrpLcphonecompleterateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int countByExample(TPrpLcphonecompleterateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int deleteByExample(TPrpLcphonecompleterateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int deleteByPrimaryKey(TPrpLcphonecompleterateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int insert(TPrpLcphonecompleterate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int insertSelective(TPrpLcphonecompleterate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    List<TPrpLcphonecompleterate> selectByExample(TPrpLcphonecompleterateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    TPrpLcphonecompleterate selectByPrimaryKey(TPrpLcphonecompleterateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TPrpLcphonecompleterate record, @Param("example") TPrpLcphonecompleterateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByExample(@Param("record") TPrpLcphonecompleterate record, @Param("example") TPrpLcphonecompleterateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByPrimaryKeySelective(TPrpLcphonecompleterate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPHONECOMPLETERATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByPrimaryKey(TPrpLcphonecompleterate record);

	List<Map> exportExcel(Map paramMap);
}