package com.sinosoft.ummp.domain.mapper;

import com.sinosoft.ummp.domain.model.TPrpLcquotadata;
import com.sinosoft.ummp.domain.model.TPrpLcquotadataExample;
import com.sinosoft.ummp.domain.model.TPrpLcquotadataKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPrpLcquotadataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    int countByExample(TPrpLcquotadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    int deleteByExample(TPrpLcquotadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    int deleteByPrimaryKey(TPrpLcquotadataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    int insert(TPrpLcquotadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    int insertSelective(TPrpLcquotadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    List<TPrpLcquotadata> selectByExample(TPrpLcquotadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    TPrpLcquotadata selectByPrimaryKey(TPrpLcquotadataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") TPrpLcquotadata record, @Param("example") TPrpLcquotadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    int updateByExample(@Param("record") TPrpLcquotadata record, @Param("example") TPrpLcquotadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    int updateByPrimaryKeySelective(TPrpLcquotadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCQUOTADATA
     *
     * @mbggenerated Thu Sep 29 19:20:19 CST 2016
     */
    int updateByPrimaryKey(TPrpLcquotadata record);
}