package com.sinosoft.ummp.domain.mapper;

import com.sinosoft.ummp.domain.model.TPrpLcpreservationperiod;
import com.sinosoft.ummp.domain.model.TPrpLcpreservationperiodExample;
import com.sinosoft.ummp.domain.model.TPrpLcpreservationperiodKey;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TPrpLcpreservationperiodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int countByExample(TPrpLcpreservationperiodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int deleteByExample(TPrpLcpreservationperiodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int deleteByPrimaryKey(TPrpLcpreservationperiodKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int insert(TPrpLcpreservationperiod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int insertSelective(TPrpLcpreservationperiod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    List<TPrpLcpreservationperiod> selectByExample(TPrpLcpreservationperiodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    TPrpLcpreservationperiod selectByPrimaryKey(TPrpLcpreservationperiodKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TPrpLcpreservationperiod record, @Param("example") TPrpLcpreservationperiodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByExample(@Param("record") TPrpLcpreservationperiod record, @Param("example") TPrpLcpreservationperiodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByPrimaryKeySelective(TPrpLcpreservationperiod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCPRESERVATIONPERIOD
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByPrimaryKey(TPrpLcpreservationperiod record);

	List<Map> exportExcel(Map paramMap);
}