package com.sinosoft.ummp.domain.mapper;

import com.sinosoft.ummp.domain.model.TPrpLcclaimgetrate;
import com.sinosoft.ummp.domain.model.TPrpLcclaimgetrateExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TPrpLcclaimgetrateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int countByExample(TPrpLcclaimgetrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int deleteByExample(TPrpLcclaimgetrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int insert(TPrpLcclaimgetrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int insertSelective(TPrpLcclaimgetrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    List<TPrpLcclaimgetrate> selectByExample(TPrpLcclaimgetrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    TPrpLcclaimgetrate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TPrpLcclaimgetrate record, @Param("example") TPrpLcclaimgetrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByExample(@Param("record") TPrpLcclaimgetrate record, @Param("example") TPrpLcclaimgetrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByPrimaryKeySelective(TPrpLcclaimgetrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCCLAIMGETRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByPrimaryKey(TPrpLcclaimgetrate record);

	List<Map> exportExcel(Map paramMap);
}