package com.sinosoft.ummp.domain.mapper;

import com.sinosoft.ummp.domain.model.TPrpLcreviewsuccessrate;
import com.sinosoft.ummp.domain.model.TPrpLcreviewsuccessrateExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TPrpLcreviewsuccessrateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int countByExample(TPrpLcreviewsuccessrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int deleteByExample(TPrpLcreviewsuccessrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int insert(TPrpLcreviewsuccessrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int insertSelective(TPrpLcreviewsuccessrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    List<TPrpLcreviewsuccessrate> selectByExample(TPrpLcreviewsuccessrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    TPrpLcreviewsuccessrate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") TPrpLcreviewsuccessrate record, @Param("example") TPrpLcreviewsuccessrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByExample(@Param("record") TPrpLcreviewsuccessrate record, @Param("example") TPrpLcreviewsuccessrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByPrimaryKeySelective(TPrpLcreviewsuccessrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRP_LCREVIEWSUCCESSRATE
     *
     * @mbggenerated Tue Sep 27 16:54:58 CST 2016
     */
    int updateByPrimaryKey(TPrpLcreviewsuccessrate record);

	List<Map> exportExcel(Map paramMap);
}