package com.sinosoft.ummp.domain.mapper;

import com.sinosoft.ummp.domain.model.TShiaSynchroRiskInfo;
import com.sinosoft.ummp.domain.model.TShiaSynchroRiskInfoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TShiaSynchroRiskInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    int countByExample(TShiaSynchroRiskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    int deleteByExample(TShiaSynchroRiskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    int insert(TShiaSynchroRiskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    int insertSelective(TShiaSynchroRiskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    List<TShiaSynchroRiskInfo> selectByExample(TShiaSynchroRiskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    TShiaSynchroRiskInfo selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") TShiaSynchroRiskInfo record, @Param("example") TShiaSynchroRiskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    int updateByExample(@Param("record") TShiaSynchroRiskInfo record, @Param("example") TShiaSynchroRiskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    int updateByPrimaryKeySelective(TShiaSynchroRiskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SHIA_SYNCHRO_RISK_INFO
     *
     * @mbggenerated Wed Sep 21 15:30:23 CST 2016
     */
    int updateByPrimaryKey(TShiaSynchroRiskInfo record);
}