package com.sinosoft.ummp.domain.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ummp.domain.model.TTempNode;
import com.sinosoft.ummp.domain.model.TTempNodeExample;

public interface TTempNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    int countByExample(TTempNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    int deleteByExample(TTempNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    int insert(TTempNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    int insertSelective(TTempNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    List<TTempNode> selectByExample(TTempNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    TTempNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") TTempNode record, @Param("example") TTempNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    int updateByExample(@Param("record") TTempNode record, @Param("example") TTempNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    int updateByPrimaryKeySelective(TTempNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TEMP_NODE
     *
     * @mbggenerated Tue Jun 21 11:07:32 CST 2016
     */
    int updateByPrimaryKey(TTempNode record);
    
    /**
     * 获取节点对应的Sql信息
     * @param id
     * @return
     */
	Map<String,String> selectNodeSqlInfo(Integer id);
	/**
	 * 根据ID递归删除
	 * @param id
	 * @return
	 */
	int deleteByIdRecurs(Integer id);
	/**
	 * 根据ID递归查询，包括ID本身的记录
	 * @param id
	 * @return
	 */
	List<TTempNode> selecteByIdRecurs(Integer id);
	/**
	 * 根据父类ID查询所有子类
	 * @param fid
	 * @return
	 */
	List<TTempNode> selectTempNodeByFid(Integer fid);
	/**
	 * 根据NODE_ID 递归删除
	 * @param nodeId
	 * @return
	 */
	int deleteByNodeIdRecurs(BigDecimal nodeId);
	/**
	 * 根据根节点显示数据
	 * @return
	 */
	List<TTempNode> selectTempRootNode();
	/**
	 * 通过父类ID获取对应信息
	 * @param fid
	 * @return
	 */
	List<TTempNode> selectTempByFId(Integer fid);
}