package com.sinosoft.platform.quartz.domain.model;

public class QrtzPausedTriggerGrps {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    private String triggerGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
     *
     * @return the value of QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
     *
     * @param triggerGroup the value for QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
     *
     * @mbggenerated Mon Jun 06 17:03:54 CST 2016
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }
}